package com.bryllyant.kona.app.entity;

import java.io.Serializable;

public class AuthCode extends KBaseAuthCode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__auth_code
     *
     * @mbg.generated Mon Mar 05 08:53:26 EST 2018
     */
    private static final long serialVersionUID = 1L;
}