package com.bryllyant.kona.app.entity;

import com.bryllyant.kona.app.entity.BaseCampaignChannel.ReplyStrategy;
import com.bryllyant.kona.app.entity.BaseCampaignChannel.TargetStrategy;
import com.bryllyant.kona.app.entity.BaseCampaignChannel.Type;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CampaignChannelExample implements com.bryllyant.kona.data.mybatis.KEntityExample<CampaignChannelExample.Criteria> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private Integer limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private String fts;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public CampaignChannelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setFts(String fts) {
        this.fts = fts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public String getFts() {
        return fts;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("`uid` is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("`uid` is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("`uid` =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("`uid` <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("`uid` >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("`uid` >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("`uid` <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("`uid` <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("`uid` like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("`uid` not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("`uid` in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("`uid` not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("`uid` between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("`uid` not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andCampaignIdIsNull() {
            addCriterion("`campaign_id` is null");
            return (Criteria) this;
        }

        public Criteria andCampaignIdIsNotNull() {
            addCriterion("`campaign_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCampaignIdEqualTo(Long value) {
            addCriterion("`campaign_id` =", value, "campaignId");
            return (Criteria) this;
        }

        public Criteria andCampaignIdNotEqualTo(Long value) {
            addCriterion("`campaign_id` <>", value, "campaignId");
            return (Criteria) this;
        }

        public Criteria andCampaignIdGreaterThan(Long value) {
            addCriterion("`campaign_id` >", value, "campaignId");
            return (Criteria) this;
        }

        public Criteria andCampaignIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`campaign_id` >=", value, "campaignId");
            return (Criteria) this;
        }

        public Criteria andCampaignIdLessThan(Long value) {
            addCriterion("`campaign_id` <", value, "campaignId");
            return (Criteria) this;
        }

        public Criteria andCampaignIdLessThanOrEqualTo(Long value) {
            addCriterion("`campaign_id` <=", value, "campaignId");
            return (Criteria) this;
        }

        public Criteria andCampaignIdIn(List<Long> values) {
            addCriterion("`campaign_id` in", values, "campaignId");
            return (Criteria) this;
        }

        public Criteria andCampaignIdNotIn(List<Long> values) {
            addCriterion("`campaign_id` not in", values, "campaignId");
            return (Criteria) this;
        }

        public Criteria andCampaignIdBetween(Long value1, Long value2) {
            addCriterion("`campaign_id` between", value1, value2, "campaignId");
            return (Criteria) this;
        }

        public Criteria andCampaignIdNotBetween(Long value1, Long value2) {
            addCriterion("`campaign_id` not between", value1, value2, "campaignId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("`group_id` is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("`group_id` is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(Long value) {
            addCriterion("`group_id` =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(Long value) {
            addCriterion("`group_id` <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(Long value) {
            addCriterion("`group_id` >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`group_id` >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(Long value) {
            addCriterion("`group_id` <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(Long value) {
            addCriterion("`group_id` <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<Long> values) {
            addCriterion("`group_id` in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<Long> values) {
            addCriterion("`group_id` not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(Long value1, Long value2) {
            addCriterion("`group_id` between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(Long value1, Long value2) {
            addCriterion("`group_id` not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andPromoCodeIsNull() {
            addCriterion("`promo_code` is null");
            return (Criteria) this;
        }

        public Criteria andPromoCodeIsNotNull() {
            addCriterion("`promo_code` is not null");
            return (Criteria) this;
        }

        public Criteria andPromoCodeEqualTo(String value) {
            addCriterion("`promo_code` =", value, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeNotEqualTo(String value) {
            addCriterion("`promo_code` <>", value, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeGreaterThan(String value) {
            addCriterion("`promo_code` >", value, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeGreaterThanOrEqualTo(String value) {
            addCriterion("`promo_code` >=", value, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeLessThan(String value) {
            addCriterion("`promo_code` <", value, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeLessThanOrEqualTo(String value) {
            addCriterion("`promo_code` <=", value, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeLike(String value) {
            addCriterion("`promo_code` like", value, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeNotLike(String value) {
            addCriterion("`promo_code` not like", value, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeIn(List<String> values) {
            addCriterion("`promo_code` in", values, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeNotIn(List<String> values) {
            addCriterion("`promo_code` not in", values, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeBetween(String value1, String value2) {
            addCriterion("`promo_code` between", value1, value2, "promoCode");
            return (Criteria) this;
        }

        public Criteria andPromoCodeNotBetween(String value1, String value2) {
            addCriterion("`promo_code` not between", value1, value2, "promoCode");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Type value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Type value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Type value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Type value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Type value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Type value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(Type value) {
            addCriterion("`type` like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(Type value) {
            addCriterion("`type` not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Type> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Type> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Type value1, Type value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Type value1, Type value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyIsNull() {
            addCriterion("`target_strategy` is null");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyIsNotNull() {
            addCriterion("`target_strategy` is not null");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyEqualTo(TargetStrategy value) {
            addCriterion("`target_strategy` =", value, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyNotEqualTo(TargetStrategy value) {
            addCriterion("`target_strategy` <>", value, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyGreaterThan(TargetStrategy value) {
            addCriterion("`target_strategy` >", value, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyGreaterThanOrEqualTo(TargetStrategy value) {
            addCriterion("`target_strategy` >=", value, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyLessThan(TargetStrategy value) {
            addCriterion("`target_strategy` <", value, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyLessThanOrEqualTo(TargetStrategy value) {
            addCriterion("`target_strategy` <=", value, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyLike(TargetStrategy value) {
            addCriterion("`target_strategy` like", value, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyNotLike(TargetStrategy value) {
            addCriterion("`target_strategy` not like", value, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyIn(List<TargetStrategy> values) {
            addCriterion("`target_strategy` in", values, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyNotIn(List<TargetStrategy> values) {
            addCriterion("`target_strategy` not in", values, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyBetween(TargetStrategy value1, TargetStrategy value2) {
            addCriterion("`target_strategy` between", value1, value2, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andTargetStrategyNotBetween(TargetStrategy value1, TargetStrategy value2) {
            addCriterion("`target_strategy` not between", value1, value2, "targetStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyIsNull() {
            addCriterion("`reply_strategy` is null");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyIsNotNull() {
            addCriterion("`reply_strategy` is not null");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyEqualTo(ReplyStrategy value) {
            addCriterion("`reply_strategy` =", value, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyNotEqualTo(ReplyStrategy value) {
            addCriterion("`reply_strategy` <>", value, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyGreaterThan(ReplyStrategy value) {
            addCriterion("`reply_strategy` >", value, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyGreaterThanOrEqualTo(ReplyStrategy value) {
            addCriterion("`reply_strategy` >=", value, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyLessThan(ReplyStrategy value) {
            addCriterion("`reply_strategy` <", value, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyLessThanOrEqualTo(ReplyStrategy value) {
            addCriterion("`reply_strategy` <=", value, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyLike(ReplyStrategy value) {
            addCriterion("`reply_strategy` like", value, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyNotLike(ReplyStrategy value) {
            addCriterion("`reply_strategy` not like", value, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyIn(List<ReplyStrategy> values) {
            addCriterion("`reply_strategy` in", values, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyNotIn(List<ReplyStrategy> values) {
            addCriterion("`reply_strategy` not in", values, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyBetween(ReplyStrategy value1, ReplyStrategy value2) {
            addCriterion("`reply_strategy` between", value1, value2, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andReplyStrategyNotBetween(ReplyStrategy value1, ReplyStrategy value2) {
            addCriterion("`reply_strategy` not between", value1, value2, "replyStrategy");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSlugIsNull() {
            addCriterion("`slug` is null");
            return (Criteria) this;
        }

        public Criteria andSlugIsNotNull() {
            addCriterion("`slug` is not null");
            return (Criteria) this;
        }

        public Criteria andSlugEqualTo(String value) {
            addCriterion("`slug` =", value, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugNotEqualTo(String value) {
            addCriterion("`slug` <>", value, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugGreaterThan(String value) {
            addCriterion("`slug` >", value, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugGreaterThanOrEqualTo(String value) {
            addCriterion("`slug` >=", value, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugLessThan(String value) {
            addCriterion("`slug` <", value, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugLessThanOrEqualTo(String value) {
            addCriterion("`slug` <=", value, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugLike(String value) {
            addCriterion("`slug` like", value, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugNotLike(String value) {
            addCriterion("`slug` not like", value, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugIn(List<String> values) {
            addCriterion("`slug` in", values, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugNotIn(List<String> values) {
            addCriterion("`slug` not in", values, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugBetween(String value1, String value2) {
            addCriterion("`slug` between", value1, value2, "slug");
            return (Criteria) this;
        }

        public Criteria andSlugNotBetween(String value1, String value2) {
            addCriterion("`slug` not between", value1, value2, "slug");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsIsNull() {
            addCriterion("`adwords_keywords` is null");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsIsNotNull() {
            addCriterion("`adwords_keywords` is not null");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsEqualTo(String value) {
            addCriterion("`adwords_keywords` =", value, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsNotEqualTo(String value) {
            addCriterion("`adwords_keywords` <>", value, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsGreaterThan(String value) {
            addCriterion("`adwords_keywords` >", value, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("`adwords_keywords` >=", value, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsLessThan(String value) {
            addCriterion("`adwords_keywords` <", value, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsLessThanOrEqualTo(String value) {
            addCriterion("`adwords_keywords` <=", value, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsLike(String value) {
            addCriterion("`adwords_keywords` like", value, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsNotLike(String value) {
            addCriterion("`adwords_keywords` not like", value, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsIn(List<String> values) {
            addCriterion("`adwords_keywords` in", values, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsNotIn(List<String> values) {
            addCriterion("`adwords_keywords` not in", values, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsBetween(String value1, String value2) {
            addCriterion("`adwords_keywords` between", value1, value2, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andAdwordsKeywordsNotBetween(String value1, String value2) {
            addCriterion("`adwords_keywords` not between", value1, value2, "adwordsKeywords");
            return (Criteria) this;
        }

        public Criteria andSmsNumberIsNull() {
            addCriterion("`sms_number` is null");
            return (Criteria) this;
        }

        public Criteria andSmsNumberIsNotNull() {
            addCriterion("`sms_number` is not null");
            return (Criteria) this;
        }

        public Criteria andSmsNumberEqualTo(String value) {
            addCriterion("`sms_number` =", value, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberNotEqualTo(String value) {
            addCriterion("`sms_number` <>", value, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberGreaterThan(String value) {
            addCriterion("`sms_number` >", value, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberGreaterThanOrEqualTo(String value) {
            addCriterion("`sms_number` >=", value, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberLessThan(String value) {
            addCriterion("`sms_number` <", value, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberLessThanOrEqualTo(String value) {
            addCriterion("`sms_number` <=", value, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberLike(String value) {
            addCriterion("`sms_number` like", value, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberNotLike(String value) {
            addCriterion("`sms_number` not like", value, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberIn(List<String> values) {
            addCriterion("`sms_number` in", values, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberNotIn(List<String> values) {
            addCriterion("`sms_number` not in", values, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberBetween(String value1, String value2) {
            addCriterion("`sms_number` between", value1, value2, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsNumberNotBetween(String value1, String value2) {
            addCriterion("`sms_number` not between", value1, value2, "smsNumber");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordIsNull() {
            addCriterion("`sms_keyword` is null");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordIsNotNull() {
            addCriterion("`sms_keyword` is not null");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordEqualTo(String value) {
            addCriterion("`sms_keyword` =", value, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordNotEqualTo(String value) {
            addCriterion("`sms_keyword` <>", value, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordGreaterThan(String value) {
            addCriterion("`sms_keyword` >", value, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("`sms_keyword` >=", value, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordLessThan(String value) {
            addCriterion("`sms_keyword` <", value, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordLessThanOrEqualTo(String value) {
            addCriterion("`sms_keyword` <=", value, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordLike(String value) {
            addCriterion("`sms_keyword` like", value, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordNotLike(String value) {
            addCriterion("`sms_keyword` not like", value, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordIn(List<String> values) {
            addCriterion("`sms_keyword` in", values, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordNotIn(List<String> values) {
            addCriterion("`sms_keyword` not in", values, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordBetween(String value1, String value2) {
            addCriterion("`sms_keyword` between", value1, value2, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andSmsKeywordNotBetween(String value1, String value2) {
            addCriterion("`sms_keyword` not between", value1, value2, "smsKeyword");
            return (Criteria) this;
        }

        public Criteria andShortUrlIsNull() {
            addCriterion("`short_url` is null");
            return (Criteria) this;
        }

        public Criteria andShortUrlIsNotNull() {
            addCriterion("`short_url` is not null");
            return (Criteria) this;
        }

        public Criteria andShortUrlEqualTo(String value) {
            addCriterion("`short_url` =", value, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlNotEqualTo(String value) {
            addCriterion("`short_url` <>", value, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlGreaterThan(String value) {
            addCriterion("`short_url` >", value, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlGreaterThanOrEqualTo(String value) {
            addCriterion("`short_url` >=", value, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlLessThan(String value) {
            addCriterion("`short_url` <", value, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlLessThanOrEqualTo(String value) {
            addCriterion("`short_url` <=", value, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlLike(String value) {
            addCriterion("`short_url` like", value, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlNotLike(String value) {
            addCriterion("`short_url` not like", value, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlIn(List<String> values) {
            addCriterion("`short_url` in", values, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlNotIn(List<String> values) {
            addCriterion("`short_url` not in", values, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlBetween(String value1, String value2) {
            addCriterion("`short_url` between", value1, value2, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andShortUrlNotBetween(String value1, String value2) {
            addCriterion("`short_url` not between", value1, value2, "shortUrl");
            return (Criteria) this;
        }

        public Criteria andConversionCountIsNull() {
            addCriterion("`conversion_count` is null");
            return (Criteria) this;
        }

        public Criteria andConversionCountIsNotNull() {
            addCriterion("`conversion_count` is not null");
            return (Criteria) this;
        }

        public Criteria andConversionCountEqualTo(Integer value) {
            addCriterion("`conversion_count` =", value, "conversionCount");
            return (Criteria) this;
        }

        public Criteria andConversionCountNotEqualTo(Integer value) {
            addCriterion("`conversion_count` <>", value, "conversionCount");
            return (Criteria) this;
        }

        public Criteria andConversionCountGreaterThan(Integer value) {
            addCriterion("`conversion_count` >", value, "conversionCount");
            return (Criteria) this;
        }

        public Criteria andConversionCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("`conversion_count` >=", value, "conversionCount");
            return (Criteria) this;
        }

        public Criteria andConversionCountLessThan(Integer value) {
            addCriterion("`conversion_count` <", value, "conversionCount");
            return (Criteria) this;
        }

        public Criteria andConversionCountLessThanOrEqualTo(Integer value) {
            addCriterion("`conversion_count` <=", value, "conversionCount");
            return (Criteria) this;
        }

        public Criteria andConversionCountIn(List<Integer> values) {
            addCriterion("`conversion_count` in", values, "conversionCount");
            return (Criteria) this;
        }

        public Criteria andConversionCountNotIn(List<Integer> values) {
            addCriterion("`conversion_count` not in", values, "conversionCount");
            return (Criteria) this;
        }

        public Criteria andConversionCountBetween(Integer value1, Integer value2) {
            addCriterion("`conversion_count` between", value1, value2, "conversionCount");
            return (Criteria) this;
        }

        public Criteria andConversionCountNotBetween(Integer value1, Integer value2) {
            addCriterion("`conversion_count` not between", value1, value2, "conversionCount");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("`enabled` is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("`enabled` is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(boolean value) {
            addCriterion("`enabled` =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(boolean value) {
            addCriterion("`enabled` <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(boolean value) {
            addCriterion("`enabled` >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(boolean value) {
            addCriterion("`enabled` >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(boolean value) {
            addCriterion("`enabled` <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(boolean value) {
            addCriterion("`enabled` <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Boolean> values) {
            addCriterion("`enabled` in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Boolean> values) {
            addCriterion("`enabled` not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(boolean value1, boolean value2) {
            addCriterion("`enabled` between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(boolean value1, boolean value2) {
            addCriterion("`enabled` not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledIsNull() {
            addCriterion("`reply_enabled` is null");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledIsNotNull() {
            addCriterion("`reply_enabled` is not null");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledEqualTo(boolean value) {
            addCriterion("`reply_enabled` =", value, "replyEnabled");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledNotEqualTo(boolean value) {
            addCriterion("`reply_enabled` <>", value, "replyEnabled");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledGreaterThan(boolean value) {
            addCriterion("`reply_enabled` >", value, "replyEnabled");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledGreaterThanOrEqualTo(boolean value) {
            addCriterion("`reply_enabled` >=", value, "replyEnabled");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledLessThan(boolean value) {
            addCriterion("`reply_enabled` <", value, "replyEnabled");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledLessThanOrEqualTo(boolean value) {
            addCriterion("`reply_enabled` <=", value, "replyEnabled");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledIn(List<Boolean> values) {
            addCriterion("`reply_enabled` in", values, "replyEnabled");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledNotIn(List<Boolean> values) {
            addCriterion("`reply_enabled` not in", values, "replyEnabled");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledBetween(boolean value1, boolean value2) {
            addCriterion("`reply_enabled` between", value1, value2, "replyEnabled");
            return (Criteria) this;
        }

        public Criteria andReplyEnabledNotBetween(boolean value1, boolean value2) {
            addCriterion("`reply_enabled` not between", value1, value2, "replyEnabled");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("`start_date` is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("`start_date` is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(Date value) {
            addCriterion("`start_date` =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(Date value) {
            addCriterion("`start_date` <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(Date value) {
            addCriterion("`start_date` >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`start_date` >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(Date value) {
            addCriterion("`start_date` <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(Date value) {
            addCriterion("`start_date` <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<Date> values) {
            addCriterion("`start_date` in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<Date> values) {
            addCriterion("`start_date` not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(Date value1, Date value2) {
            addCriterion("`start_date` between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(Date value1, Date value2) {
            addCriterion("`start_date` not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("`end_date` is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("`end_date` is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(Date value) {
            addCriterion("`end_date` =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(Date value) {
            addCriterion("`end_date` <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(Date value) {
            addCriterion("`end_date` >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`end_date` >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(Date value) {
            addCriterion("`end_date` <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(Date value) {
            addCriterion("`end_date` <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<Date> values) {
            addCriterion("`end_date` in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<Date> values) {
            addCriterion("`end_date` not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(Date value1, Date value2) {
            addCriterion("`end_date` between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(Date value1, Date value2) {
            addCriterion("`end_date` not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("`created_date` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("`created_date` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("`created_date` =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("`created_date` <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("`created_date` >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`created_date` >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("`created_date` <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("`created_date` <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("`created_date` in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("`created_date` not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("`created_date` between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("`created_date` not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNull() {
            addCriterion("`updated_date` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNotNull() {
            addCriterion("`updated_date` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateEqualTo(Date value) {
            addCriterion("`updated_date` =", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotEqualTo(Date value) {
            addCriterion("`updated_date` <>", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThan(Date value) {
            addCriterion("`updated_date` >", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`updated_date` >=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThan(Date value) {
            addCriterion("`updated_date` <", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterion("`updated_date` <=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIn(List<Date> values) {
            addCriterion("`updated_date` in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotIn(List<Date> values) {
            addCriterion("`updated_date` not in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateBetween(Date value1, Date value2) {
            addCriterion("`updated_date` between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterion("`updated_date` not between", value1, value2, "updatedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated do_not_delete_during_merge Thu May 10 08:22:09 EDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__campaign_channel
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}