package com.bryllyant.kona.app.entity;

import java.io.Serializable;

public class CampaignEvent extends KBaseCampaignEvent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    private static final long serialVersionUID = 1L;
}