package com.bryllyant.kona.app.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CartExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private Integer limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public CartExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("`uid` is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("`uid` is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("`uid` =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("`uid` <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("`uid` >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("`uid` >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("`uid` <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("`uid` <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("`uid` like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("`uid` not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("`uid` in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("`uid` not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("`uid` between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("`uid` not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("`app_id` is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("`app_id` is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(Long value) {
            addCriterion("`app_id` =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(Long value) {
            addCriterion("`app_id` <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(Long value) {
            addCriterion("`app_id` >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`app_id` >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(Long value) {
            addCriterion("`app_id` <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(Long value) {
            addCriterion("`app_id` <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<Long> values) {
            addCriterion("`app_id` in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<Long> values) {
            addCriterion("`app_id` not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(Long value1, Long value2) {
            addCriterion("`app_id` between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(Long value1, Long value2) {
            addCriterion("`app_id` not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("`user_id` is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("`user_id` is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("`user_id` =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("`user_id` <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("`user_id` >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`user_id` >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("`user_id` <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("`user_id` <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("`user_id` in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("`user_id` not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("`user_id` between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("`user_id` not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("`account_id` is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("`account_id` is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(Long value) {
            addCriterion("`account_id` =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(Long value) {
            addCriterion("`account_id` <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(Long value) {
            addCriterion("`account_id` >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`account_id` >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(Long value) {
            addCriterion("`account_id` <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(Long value) {
            addCriterion("`account_id` <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<Long> values) {
            addCriterion("`account_id` in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<Long> values) {
            addCriterion("`account_id` not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(Long value1, Long value2) {
            addCriterion("`account_id` between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(Long value1, Long value2) {
            addCriterion("`account_id` not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdIsNull() {
            addCriterion("`currency_id` is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdIsNotNull() {
            addCriterion("`currency_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdEqualTo(Long value) {
            addCriterion("`currency_id` =", value, "currencyId");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdNotEqualTo(Long value) {
            addCriterion("`currency_id` <>", value, "currencyId");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdGreaterThan(Long value) {
            addCriterion("`currency_id` >", value, "currencyId");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`currency_id` >=", value, "currencyId");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdLessThan(Long value) {
            addCriterion("`currency_id` <", value, "currencyId");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdLessThanOrEqualTo(Long value) {
            addCriterion("`currency_id` <=", value, "currencyId");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdIn(List<Long> values) {
            addCriterion("`currency_id` in", values, "currencyId");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdNotIn(List<Long> values) {
            addCriterion("`currency_id` not in", values, "currencyId");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdBetween(Long value1, Long value2) {
            addCriterion("`currency_id` between", value1, value2, "currencyId");
            return (Criteria) this;
        }

        public Criteria andCurrencyIdNotBetween(Long value1, Long value2) {
            addCriterion("`currency_id` not between", value1, value2, "currencyId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIsNull() {
            addCriterion("`invoice_id` is null");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIsNotNull() {
            addCriterion("`invoice_id` is not null");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdEqualTo(Long value) {
            addCriterion("`invoice_id` =", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotEqualTo(Long value) {
            addCriterion("`invoice_id` <>", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdGreaterThan(Long value) {
            addCriterion("`invoice_id` >", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`invoice_id` >=", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdLessThan(Long value) {
            addCriterion("`invoice_id` <", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdLessThanOrEqualTo(Long value) {
            addCriterion("`invoice_id` <=", value, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdIn(List<Long> values) {
            addCriterion("`invoice_id` in", values, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotIn(List<Long> values) {
            addCriterion("`invoice_id` not in", values, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdBetween(Long value1, Long value2) {
            addCriterion("`invoice_id` between", value1, value2, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andInvoiceIdNotBetween(Long value1, Long value2) {
            addCriterion("`invoice_id` not between", value1, value2, "invoiceId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNull() {
            addCriterion("`session_id` is null");
            return (Criteria) this;
        }

        public Criteria andSessionIdIsNotNull() {
            addCriterion("`session_id` is not null");
            return (Criteria) this;
        }

        public Criteria andSessionIdEqualTo(String value) {
            addCriterion("`session_id` =", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotEqualTo(String value) {
            addCriterion("`session_id` <>", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThan(String value) {
            addCriterion("`session_id` >", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdGreaterThanOrEqualTo(String value) {
            addCriterion("`session_id` >=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThan(String value) {
            addCriterion("`session_id` <", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLessThanOrEqualTo(String value) {
            addCriterion("`session_id` <=", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdLike(String value) {
            addCriterion("`session_id` like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotLike(String value) {
            addCriterion("`session_id` not like", value, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdIn(List<String> values) {
            addCriterion("`session_id` in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotIn(List<String> values) {
            addCriterion("`session_id` not in", values, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdBetween(String value1, String value2) {
            addCriterion("`session_id` between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andSessionIdNotBetween(String value1, String value2) {
            addCriterion("`session_id` not between", value1, value2, "sessionId");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIsNull() {
            addCriterion("`access_token` is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIsNotNull() {
            addCriterion("`access_token` is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenEqualTo(String value) {
            addCriterion("`access_token` =", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotEqualTo(String value) {
            addCriterion("`access_token` <>", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenGreaterThan(String value) {
            addCriterion("`access_token` >", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("`access_token` >=", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenLessThan(String value) {
            addCriterion("`access_token` <", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("`access_token` <=", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenLike(String value) {
            addCriterion("`access_token` like", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotLike(String value) {
            addCriterion("`access_token` not like", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIn(List<String> values) {
            addCriterion("`access_token` in", values, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotIn(List<String> values) {
            addCriterion("`access_token` not in", values, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenBetween(String value1, String value2) {
            addCriterion("`access_token` between", value1, value2, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotBetween(String value1, String value2) {
            addCriterion("`access_token` not between", value1, value2, "accessToken");
            return (Criteria) this;
        }

        public Criteria andHostnameIsNull() {
            addCriterion("`hostname` is null");
            return (Criteria) this;
        }

        public Criteria andHostnameIsNotNull() {
            addCriterion("`hostname` is not null");
            return (Criteria) this;
        }

        public Criteria andHostnameEqualTo(String value) {
            addCriterion("`hostname` =", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotEqualTo(String value) {
            addCriterion("`hostname` <>", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameGreaterThan(String value) {
            addCriterion("`hostname` >", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameGreaterThanOrEqualTo(String value) {
            addCriterion("`hostname` >=", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLessThan(String value) {
            addCriterion("`hostname` <", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLessThanOrEqualTo(String value) {
            addCriterion("`hostname` <=", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameLike(String value) {
            addCriterion("`hostname` like", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotLike(String value) {
            addCriterion("`hostname` not like", value, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameIn(List<String> values) {
            addCriterion("`hostname` in", values, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotIn(List<String> values) {
            addCriterion("`hostname` not in", values, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameBetween(String value1, String value2) {
            addCriterion("`hostname` between", value1, value2, "hostname");
            return (Criteria) this;
        }

        public Criteria andHostnameNotBetween(String value1, String value2) {
            addCriterion("`hostname` not between", value1, value2, "hostname");
            return (Criteria) this;
        }

        public Criteria andUserAgentIsNull() {
            addCriterion("`user_agent` is null");
            return (Criteria) this;
        }

        public Criteria andUserAgentIsNotNull() {
            addCriterion("`user_agent` is not null");
            return (Criteria) this;
        }

        public Criteria andUserAgentEqualTo(String value) {
            addCriterion("`user_agent` =", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentNotEqualTo(String value) {
            addCriterion("`user_agent` <>", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentGreaterThan(String value) {
            addCriterion("`user_agent` >", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentGreaterThanOrEqualTo(String value) {
            addCriterion("`user_agent` >=", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentLessThan(String value) {
            addCriterion("`user_agent` <", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentLessThanOrEqualTo(String value) {
            addCriterion("`user_agent` <=", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentLike(String value) {
            addCriterion("`user_agent` like", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentNotLike(String value) {
            addCriterion("`user_agent` not like", value, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentIn(List<String> values) {
            addCriterion("`user_agent` in", values, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentNotIn(List<String> values) {
            addCriterion("`user_agent` not in", values, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentBetween(String value1, String value2) {
            addCriterion("`user_agent` between", value1, value2, "userAgent");
            return (Criteria) this;
        }

        public Criteria andUserAgentNotBetween(String value1, String value2) {
            addCriterion("`user_agent` not between", value1, value2, "userAgent");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("`latitude` is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("`latitude` is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(Double value) {
            addCriterion("`latitude` =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(Double value) {
            addCriterion("`latitude` <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(Double value) {
            addCriterion("`latitude` >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("`latitude` >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(Double value) {
            addCriterion("`latitude` <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("`latitude` <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<Double> values) {
            addCriterion("`latitude` in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<Double> values) {
            addCriterion("`latitude` not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(Double value1, Double value2) {
            addCriterion("`latitude` between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("`latitude` not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("`longitude` is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("`longitude` is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(Double value) {
            addCriterion("`longitude` =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(Double value) {
            addCriterion("`longitude` <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(Double value) {
            addCriterion("`longitude` >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("`longitude` >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(Double value) {
            addCriterion("`longitude` <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("`longitude` <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<Double> values) {
            addCriterion("`longitude` in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<Double> values) {
            addCriterion("`longitude` not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(Double value1, Double value2) {
            addCriterion("`longitude` between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("`longitude` not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andCoordsIsNull() {
            addCriterion("`coords` is null");
            return (Criteria) this;
        }

        public Criteria andCoordsIsNotNull() {
            addCriterion("`coords` is not null");
            return (Criteria) this;
        }

        public Criteria andCoordsEqualTo(Object value) {
            addCriterion("`coords` =", value, "coords");
            return (Criteria) this;
        }

        public Criteria andCoordsNotEqualTo(Object value) {
            addCriterion("`coords` <>", value, "coords");
            return (Criteria) this;
        }

        public Criteria andCoordsGreaterThan(Object value) {
            addCriterion("`coords` >", value, "coords");
            return (Criteria) this;
        }

        public Criteria andCoordsGreaterThanOrEqualTo(Object value) {
            addCriterion("`coords` >=", value, "coords");
            return (Criteria) this;
        }

        public Criteria andCoordsLessThan(Object value) {
            addCriterion("`coords` <", value, "coords");
            return (Criteria) this;
        }

        public Criteria andCoordsLessThanOrEqualTo(Object value) {
            addCriterion("`coords` <=", value, "coords");
            return (Criteria) this;
        }

        public Criteria andCoordsIn(List<Object> values) {
            addCriterion("`coords` in", values, "coords");
            return (Criteria) this;
        }

        public Criteria andCoordsNotIn(List<Object> values) {
            addCriterion("`coords` not in", values, "coords");
            return (Criteria) this;
        }

        public Criteria andCoordsBetween(Object value1, Object value2) {
            addCriterion("`coords` between", value1, value2, "coords");
            return (Criteria) this;
        }

        public Criteria andCoordsNotBetween(Object value1, Object value2) {
            addCriterion("`coords` not between", value1, value2, "coords");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("`description` is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("`description` is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("`description` =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("`description` <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("`description` >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("`description` >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("`description` <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("`description` <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("`description` like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("`description` not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("`description` in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("`description` not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("`description` between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("`description` not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andNotesIsNull() {
            addCriterion("`notes` is null");
            return (Criteria) this;
        }

        public Criteria andNotesIsNotNull() {
            addCriterion("`notes` is not null");
            return (Criteria) this;
        }

        public Criteria andNotesEqualTo(String value) {
            addCriterion("`notes` =", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotEqualTo(String value) {
            addCriterion("`notes` <>", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThan(String value) {
            addCriterion("`notes` >", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThanOrEqualTo(String value) {
            addCriterion("`notes` >=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThan(String value) {
            addCriterion("`notes` <", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThanOrEqualTo(String value) {
            addCriterion("`notes` <=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLike(String value) {
            addCriterion("`notes` like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotLike(String value) {
            addCriterion("`notes` not like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesIn(List<String> values) {
            addCriterion("`notes` in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotIn(List<String> values) {
            addCriterion("`notes` not in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesBetween(String value1, String value2) {
            addCriterion("`notes` between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotBetween(String value1, String value2) {
            addCriterion("`notes` not between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4IsNull() {
            addCriterion("`default_card_last4` is null");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4IsNotNull() {
            addCriterion("`default_card_last4` is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4EqualTo(String value) {
            addCriterion("`default_card_last4` =", value, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4NotEqualTo(String value) {
            addCriterion("`default_card_last4` <>", value, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4GreaterThan(String value) {
            addCriterion("`default_card_last4` >", value, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4GreaterThanOrEqualTo(String value) {
            addCriterion("`default_card_last4` >=", value, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4LessThan(String value) {
            addCriterion("`default_card_last4` <", value, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4LessThanOrEqualTo(String value) {
            addCriterion("`default_card_last4` <=", value, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4Like(String value) {
            addCriterion("`default_card_last4` like", value, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4NotLike(String value) {
            addCriterion("`default_card_last4` not like", value, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4In(List<String> values) {
            addCriterion("`default_card_last4` in", values, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4NotIn(List<String> values) {
            addCriterion("`default_card_last4` not in", values, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4Between(String value1, String value2) {
            addCriterion("`default_card_last4` between", value1, value2, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andDefaultCardLast4NotBetween(String value1, String value2) {
            addCriterion("`default_card_last4` not between", value1, value2, "defaultCardLast4");
            return (Criteria) this;
        }

        public Criteria andSubtotalIsNull() {
            addCriterion("`subtotal` is null");
            return (Criteria) this;
        }

        public Criteria andSubtotalIsNotNull() {
            addCriterion("`subtotal` is not null");
            return (Criteria) this;
        }

        public Criteria andSubtotalEqualTo(BigDecimal value) {
            addCriterion("`subtotal` =", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalNotEqualTo(BigDecimal value) {
            addCriterion("`subtotal` <>", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalGreaterThan(BigDecimal value) {
            addCriterion("`subtotal` >", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`subtotal` >=", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalLessThan(BigDecimal value) {
            addCriterion("`subtotal` <", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`subtotal` <=", value, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalIn(List<BigDecimal> values) {
            addCriterion("`subtotal` in", values, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalNotIn(List<BigDecimal> values) {
            addCriterion("`subtotal` not in", values, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`subtotal` between", value1, value2, "subtotal");
            return (Criteria) this;
        }

        public Criteria andSubtotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`subtotal` not between", value1, value2, "subtotal");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNull() {
            addCriterion("`discount` is null");
            return (Criteria) this;
        }

        public Criteria andDiscountIsNotNull() {
            addCriterion("`discount` is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountEqualTo(BigDecimal value) {
            addCriterion("`discount` =", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotEqualTo(BigDecimal value) {
            addCriterion("`discount` <>", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThan(BigDecimal value) {
            addCriterion("`discount` >", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`discount` >=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThan(BigDecimal value) {
            addCriterion("`discount` <", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`discount` <=", value, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountIn(List<BigDecimal> values) {
            addCriterion("`discount` in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotIn(List<BigDecimal> values) {
            addCriterion("`discount` not in", values, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`discount` between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andDiscountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`discount` not between", value1, value2, "discount");
            return (Criteria) this;
        }

        public Criteria andShippingIsNull() {
            addCriterion("`shipping` is null");
            return (Criteria) this;
        }

        public Criteria andShippingIsNotNull() {
            addCriterion("`shipping` is not null");
            return (Criteria) this;
        }

        public Criteria andShippingEqualTo(BigDecimal value) {
            addCriterion("`shipping` =", value, "shipping");
            return (Criteria) this;
        }

        public Criteria andShippingNotEqualTo(BigDecimal value) {
            addCriterion("`shipping` <>", value, "shipping");
            return (Criteria) this;
        }

        public Criteria andShippingGreaterThan(BigDecimal value) {
            addCriterion("`shipping` >", value, "shipping");
            return (Criteria) this;
        }

        public Criteria andShippingGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`shipping` >=", value, "shipping");
            return (Criteria) this;
        }

        public Criteria andShippingLessThan(BigDecimal value) {
            addCriterion("`shipping` <", value, "shipping");
            return (Criteria) this;
        }

        public Criteria andShippingLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`shipping` <=", value, "shipping");
            return (Criteria) this;
        }

        public Criteria andShippingIn(List<BigDecimal> values) {
            addCriterion("`shipping` in", values, "shipping");
            return (Criteria) this;
        }

        public Criteria andShippingNotIn(List<BigDecimal> values) {
            addCriterion("`shipping` not in", values, "shipping");
            return (Criteria) this;
        }

        public Criteria andShippingBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`shipping` between", value1, value2, "shipping");
            return (Criteria) this;
        }

        public Criteria andShippingNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`shipping` not between", value1, value2, "shipping");
            return (Criteria) this;
        }

        public Criteria andTaxIsNull() {
            addCriterion("`tax` is null");
            return (Criteria) this;
        }

        public Criteria andTaxIsNotNull() {
            addCriterion("`tax` is not null");
            return (Criteria) this;
        }

        public Criteria andTaxEqualTo(BigDecimal value) {
            addCriterion("`tax` =", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxNotEqualTo(BigDecimal value) {
            addCriterion("`tax` <>", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxGreaterThan(BigDecimal value) {
            addCriterion("`tax` >", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`tax` >=", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxLessThan(BigDecimal value) {
            addCriterion("`tax` <", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`tax` <=", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxIn(List<BigDecimal> values) {
            addCriterion("`tax` in", values, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxNotIn(List<BigDecimal> values) {
            addCriterion("`tax` not in", values, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`tax` between", value1, value2, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`tax` not between", value1, value2, "tax");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("`total` is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("`total` is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(BigDecimal value) {
            addCriterion("`total` =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(BigDecimal value) {
            addCriterion("`total` <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(BigDecimal value) {
            addCriterion("`total` >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`total` >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(BigDecimal value) {
            addCriterion("`total` <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`total` <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<BigDecimal> values) {
            addCriterion("`total` in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<BigDecimal> values) {
            addCriterion("`total` not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`total` between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`total` not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andCheckedOutIsNull() {
            addCriterion("`checked_out` is null");
            return (Criteria) this;
        }

        public Criteria andCheckedOutIsNotNull() {
            addCriterion("`checked_out` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckedOutEqualTo(boolean value) {
            addCriterion("`checked_out` =", value, "checkedOut");
            return (Criteria) this;
        }

        public Criteria andCheckedOutNotEqualTo(boolean value) {
            addCriterion("`checked_out` <>", value, "checkedOut");
            return (Criteria) this;
        }

        public Criteria andCheckedOutGreaterThan(boolean value) {
            addCriterion("`checked_out` >", value, "checkedOut");
            return (Criteria) this;
        }

        public Criteria andCheckedOutGreaterThanOrEqualTo(boolean value) {
            addCriterion("`checked_out` >=", value, "checkedOut");
            return (Criteria) this;
        }

        public Criteria andCheckedOutLessThan(boolean value) {
            addCriterion("`checked_out` <", value, "checkedOut");
            return (Criteria) this;
        }

        public Criteria andCheckedOutLessThanOrEqualTo(boolean value) {
            addCriterion("`checked_out` <=", value, "checkedOut");
            return (Criteria) this;
        }

        public Criteria andCheckedOutIn(List<Boolean> values) {
            addCriterion("`checked_out` in", values, "checkedOut");
            return (Criteria) this;
        }

        public Criteria andCheckedOutNotIn(List<Boolean> values) {
            addCriterion("`checked_out` not in", values, "checkedOut");
            return (Criteria) this;
        }

        public Criteria andCheckedOutBetween(boolean value1, boolean value2) {
            addCriterion("`checked_out` between", value1, value2, "checkedOut");
            return (Criteria) this;
        }

        public Criteria andCheckedOutNotBetween(boolean value1, boolean value2) {
            addCriterion("`checked_out` not between", value1, value2, "checkedOut");
            return (Criteria) this;
        }

        public Criteria andInvoicedIsNull() {
            addCriterion("`invoiced` is null");
            return (Criteria) this;
        }

        public Criteria andInvoicedIsNotNull() {
            addCriterion("`invoiced` is not null");
            return (Criteria) this;
        }

        public Criteria andInvoicedEqualTo(boolean value) {
            addCriterion("`invoiced` =", value, "invoiced");
            return (Criteria) this;
        }

        public Criteria andInvoicedNotEqualTo(boolean value) {
            addCriterion("`invoiced` <>", value, "invoiced");
            return (Criteria) this;
        }

        public Criteria andInvoicedGreaterThan(boolean value) {
            addCriterion("`invoiced` >", value, "invoiced");
            return (Criteria) this;
        }

        public Criteria andInvoicedGreaterThanOrEqualTo(boolean value) {
            addCriterion("`invoiced` >=", value, "invoiced");
            return (Criteria) this;
        }

        public Criteria andInvoicedLessThan(boolean value) {
            addCriterion("`invoiced` <", value, "invoiced");
            return (Criteria) this;
        }

        public Criteria andInvoicedLessThanOrEqualTo(boolean value) {
            addCriterion("`invoiced` <=", value, "invoiced");
            return (Criteria) this;
        }

        public Criteria andInvoicedIn(List<Boolean> values) {
            addCriterion("`invoiced` in", values, "invoiced");
            return (Criteria) this;
        }

        public Criteria andInvoicedNotIn(List<Boolean> values) {
            addCriterion("`invoiced` not in", values, "invoiced");
            return (Criteria) this;
        }

        public Criteria andInvoicedBetween(boolean value1, boolean value2) {
            addCriterion("`invoiced` between", value1, value2, "invoiced");
            return (Criteria) this;
        }

        public Criteria andInvoicedNotBetween(boolean value1, boolean value2) {
            addCriterion("`invoiced` not between", value1, value2, "invoiced");
            return (Criteria) this;
        }

        public Criteria andExpiredIsNull() {
            addCriterion("`expired` is null");
            return (Criteria) this;
        }

        public Criteria andExpiredIsNotNull() {
            addCriterion("`expired` is not null");
            return (Criteria) this;
        }

        public Criteria andExpiredEqualTo(boolean value) {
            addCriterion("`expired` =", value, "expired");
            return (Criteria) this;
        }

        public Criteria andExpiredNotEqualTo(boolean value) {
            addCriterion("`expired` <>", value, "expired");
            return (Criteria) this;
        }

        public Criteria andExpiredGreaterThan(boolean value) {
            addCriterion("`expired` >", value, "expired");
            return (Criteria) this;
        }

        public Criteria andExpiredGreaterThanOrEqualTo(boolean value) {
            addCriterion("`expired` >=", value, "expired");
            return (Criteria) this;
        }

        public Criteria andExpiredLessThan(boolean value) {
            addCriterion("`expired` <", value, "expired");
            return (Criteria) this;
        }

        public Criteria andExpiredLessThanOrEqualTo(boolean value) {
            addCriterion("`expired` <=", value, "expired");
            return (Criteria) this;
        }

        public Criteria andExpiredIn(List<Boolean> values) {
            addCriterion("`expired` in", values, "expired");
            return (Criteria) this;
        }

        public Criteria andExpiredNotIn(List<Boolean> values) {
            addCriterion("`expired` not in", values, "expired");
            return (Criteria) this;
        }

        public Criteria andExpiredBetween(boolean value1, boolean value2) {
            addCriterion("`expired` between", value1, value2, "expired");
            return (Criteria) this;
        }

        public Criteria andExpiredNotBetween(boolean value1, boolean value2) {
            addCriterion("`expired` not between", value1, value2, "expired");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateIsNull() {
            addCriterion("`checked_out_date` is null");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateIsNotNull() {
            addCriterion("`checked_out_date` is not null");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateEqualTo(Date value) {
            addCriterion("`checked_out_date` =", value, "checkedOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateNotEqualTo(Date value) {
            addCriterion("`checked_out_date` <>", value, "checkedOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateGreaterThan(Date value) {
            addCriterion("`checked_out_date` >", value, "checkedOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`checked_out_date` >=", value, "checkedOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateLessThan(Date value) {
            addCriterion("`checked_out_date` <", value, "checkedOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateLessThanOrEqualTo(Date value) {
            addCriterion("`checked_out_date` <=", value, "checkedOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateIn(List<Date> values) {
            addCriterion("`checked_out_date` in", values, "checkedOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateNotIn(List<Date> values) {
            addCriterion("`checked_out_date` not in", values, "checkedOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateBetween(Date value1, Date value2) {
            addCriterion("`checked_out_date` between", value1, value2, "checkedOutDate");
            return (Criteria) this;
        }

        public Criteria andCheckedOutDateNotBetween(Date value1, Date value2) {
            addCriterion("`checked_out_date` not between", value1, value2, "checkedOutDate");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateIsNull() {
            addCriterion("`invoiced_date` is null");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateIsNotNull() {
            addCriterion("`invoiced_date` is not null");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateEqualTo(Date value) {
            addCriterion("`invoiced_date` =", value, "invoicedDate");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateNotEqualTo(Date value) {
            addCriterion("`invoiced_date` <>", value, "invoicedDate");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateGreaterThan(Date value) {
            addCriterion("`invoiced_date` >", value, "invoicedDate");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`invoiced_date` >=", value, "invoicedDate");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateLessThan(Date value) {
            addCriterion("`invoiced_date` <", value, "invoicedDate");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateLessThanOrEqualTo(Date value) {
            addCriterion("`invoiced_date` <=", value, "invoicedDate");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateIn(List<Date> values) {
            addCriterion("`invoiced_date` in", values, "invoicedDate");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateNotIn(List<Date> values) {
            addCriterion("`invoiced_date` not in", values, "invoicedDate");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateBetween(Date value1, Date value2) {
            addCriterion("`invoiced_date` between", value1, value2, "invoicedDate");
            return (Criteria) this;
        }

        public Criteria andInvoicedDateNotBetween(Date value1, Date value2) {
            addCriterion("`invoiced_date` not between", value1, value2, "invoicedDate");
            return (Criteria) this;
        }

        public Criteria andExpiredDateIsNull() {
            addCriterion("`expired_date` is null");
            return (Criteria) this;
        }

        public Criteria andExpiredDateIsNotNull() {
            addCriterion("`expired_date` is not null");
            return (Criteria) this;
        }

        public Criteria andExpiredDateEqualTo(Date value) {
            addCriterion("`expired_date` =", value, "expiredDate");
            return (Criteria) this;
        }

        public Criteria andExpiredDateNotEqualTo(Date value) {
            addCriterion("`expired_date` <>", value, "expiredDate");
            return (Criteria) this;
        }

        public Criteria andExpiredDateGreaterThan(Date value) {
            addCriterion("`expired_date` >", value, "expiredDate");
            return (Criteria) this;
        }

        public Criteria andExpiredDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`expired_date` >=", value, "expiredDate");
            return (Criteria) this;
        }

        public Criteria andExpiredDateLessThan(Date value) {
            addCriterion("`expired_date` <", value, "expiredDate");
            return (Criteria) this;
        }

        public Criteria andExpiredDateLessThanOrEqualTo(Date value) {
            addCriterion("`expired_date` <=", value, "expiredDate");
            return (Criteria) this;
        }

        public Criteria andExpiredDateIn(List<Date> values) {
            addCriterion("`expired_date` in", values, "expiredDate");
            return (Criteria) this;
        }

        public Criteria andExpiredDateNotIn(List<Date> values) {
            addCriterion("`expired_date` not in", values, "expiredDate");
            return (Criteria) this;
        }

        public Criteria andExpiredDateBetween(Date value1, Date value2) {
            addCriterion("`expired_date` between", value1, value2, "expiredDate");
            return (Criteria) this;
        }

        public Criteria andExpiredDateNotBetween(Date value1, Date value2) {
            addCriterion("`expired_date` not between", value1, value2, "expiredDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("`created_date` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("`created_date` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("`created_date` =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("`created_date` <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("`created_date` >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`created_date` >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("`created_date` <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("`created_date` <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("`created_date` in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("`created_date` not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("`created_date` between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("`created_date` not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNull() {
            addCriterion("`updated_date` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNotNull() {
            addCriterion("`updated_date` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateEqualTo(Date value) {
            addCriterion("`updated_date` =", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotEqualTo(Date value) {
            addCriterion("`updated_date` <>", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThan(Date value) {
            addCriterion("`updated_date` >", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`updated_date` >=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThan(Date value) {
            addCriterion("`updated_date` <", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterion("`updated_date` <=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIn(List<Date> values) {
            addCriterion("`updated_date` in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotIn(List<Date> values) {
            addCriterion("`updated_date` not in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateBetween(Date value1, Date value2) {
            addCriterion("`updated_date` between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterion("`updated_date` not between", value1, value2, "updatedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__cart
     *
     * @mbg.generated do_not_delete_during_merge Sun Nov 19 04:45:21 EST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__cart
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}