package com.bryllyant.kona.app.entity;

import com.bryllyant.kona.app.entity.BaseDevice.Type;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DeviceExample implements com.bryllyant.kona.data.mybatis.KEntityExample<DeviceExample.Criteria> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private Integer limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private String fts;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public DeviceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setFts(String fts) {
        this.fts = fts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public String getFts() {
        return fts;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> capabilitiesCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            capabilitiesCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getCapabilitiesCriteria() {
            return capabilitiesCriteria;
        }

        protected void addCapabilitiesCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            capabilitiesCriteria.add(new Criterion(condition, value, "com.bryllyant.kona.util.DeviceCapabilityHandler"));
            allCriteria = null;
        }

        protected void addCapabilitiesCriterion(String condition, List value1, List value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            capabilitiesCriteria.add(new Criterion(condition, value1, value2, "com.bryllyant.kona.util.DeviceCapabilityHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || capabilitiesCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(capabilitiesCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("`uid` is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("`uid` is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("`uid` =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("`uid` <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("`uid` >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("`uid` >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("`uid` <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("`uid` <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("`uid` like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("`uid` not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("`uid` in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("`uid` not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("`uid` between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("`uid` not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Type value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Type value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Type value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Type value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Type value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Type value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(Type value) {
            addCriterion("`type` like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(Type value) {
            addCriterion("`type` not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Type> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Type> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Type value1, Type value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Type value1, Type value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("`parent_id` is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("`parent_id` is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Long value) {
            addCriterion("`parent_id` =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Long value) {
            addCriterion("`parent_id` <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Long value) {
            addCriterion("`parent_id` >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`parent_id` >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Long value) {
            addCriterion("`parent_id` <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Long value) {
            addCriterion("`parent_id` <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Long> values) {
            addCriterion("`parent_id` in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Long> values) {
            addCriterion("`parent_id` not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Long value1, Long value2) {
            addCriterion("`parent_id` between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Long value1, Long value2) {
            addCriterion("`parent_id` not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdIsNull() {
            addCriterion("`advertiser_id` is null");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdIsNotNull() {
            addCriterion("`advertiser_id` is not null");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdEqualTo(String value) {
            addCriterion("`advertiser_id` =", value, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdNotEqualTo(String value) {
            addCriterion("`advertiser_id` <>", value, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdGreaterThan(String value) {
            addCriterion("`advertiser_id` >", value, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdGreaterThanOrEqualTo(String value) {
            addCriterion("`advertiser_id` >=", value, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdLessThan(String value) {
            addCriterion("`advertiser_id` <", value, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdLessThanOrEqualTo(String value) {
            addCriterion("`advertiser_id` <=", value, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdLike(String value) {
            addCriterion("`advertiser_id` like", value, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdNotLike(String value) {
            addCriterion("`advertiser_id` not like", value, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdIn(List<String> values) {
            addCriterion("`advertiser_id` in", values, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdNotIn(List<String> values) {
            addCriterion("`advertiser_id` not in", values, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdBetween(String value1, String value2) {
            addCriterion("`advertiser_id` between", value1, value2, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andAdvertiserIdNotBetween(String value1, String value2) {
            addCriterion("`advertiser_id` not between", value1, value2, "advertiserId");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledIsNull() {
            addCriterion("`limit_ad_tracking_enabled` is null");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledIsNotNull() {
            addCriterion("`limit_ad_tracking_enabled` is not null");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledEqualTo(boolean value) {
            addCriterion("`limit_ad_tracking_enabled` =", value, "limitAdTrackingEnabled");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledNotEqualTo(boolean value) {
            addCriterion("`limit_ad_tracking_enabled` <>", value, "limitAdTrackingEnabled");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledGreaterThan(boolean value) {
            addCriterion("`limit_ad_tracking_enabled` >", value, "limitAdTrackingEnabled");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledGreaterThanOrEqualTo(boolean value) {
            addCriterion("`limit_ad_tracking_enabled` >=", value, "limitAdTrackingEnabled");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledLessThan(boolean value) {
            addCriterion("`limit_ad_tracking_enabled` <", value, "limitAdTrackingEnabled");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledLessThanOrEqualTo(boolean value) {
            addCriterion("`limit_ad_tracking_enabled` <=", value, "limitAdTrackingEnabled");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledIn(List<Boolean> values) {
            addCriterion("`limit_ad_tracking_enabled` in", values, "limitAdTrackingEnabled");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledNotIn(List<Boolean> values) {
            addCriterion("`limit_ad_tracking_enabled` not in", values, "limitAdTrackingEnabled");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledBetween(boolean value1, boolean value2) {
            addCriterion("`limit_ad_tracking_enabled` between", value1, value2, "limitAdTrackingEnabled");
            return (Criteria) this;
        }

        public Criteria andLimitAdTrackingEnabledNotBetween(boolean value1, boolean value2) {
            addCriterion("`limit_ad_tracking_enabled` not between", value1, value2, "limitAdTrackingEnabled");
            return (Criteria) this;
        }

        public Criteria andOsNameIsNull() {
            addCriterion("`os_name` is null");
            return (Criteria) this;
        }

        public Criteria andOsNameIsNotNull() {
            addCriterion("`os_name` is not null");
            return (Criteria) this;
        }

        public Criteria andOsNameEqualTo(String value) {
            addCriterion("`os_name` =", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameNotEqualTo(String value) {
            addCriterion("`os_name` <>", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameGreaterThan(String value) {
            addCriterion("`os_name` >", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameGreaterThanOrEqualTo(String value) {
            addCriterion("`os_name` >=", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameLessThan(String value) {
            addCriterion("`os_name` <", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameLessThanOrEqualTo(String value) {
            addCriterion("`os_name` <=", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameLike(String value) {
            addCriterion("`os_name` like", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameNotLike(String value) {
            addCriterion("`os_name` not like", value, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameIn(List<String> values) {
            addCriterion("`os_name` in", values, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameNotIn(List<String> values) {
            addCriterion("`os_name` not in", values, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameBetween(String value1, String value2) {
            addCriterion("`os_name` between", value1, value2, "osName");
            return (Criteria) this;
        }

        public Criteria andOsNameNotBetween(String value1, String value2) {
            addCriterion("`os_name` not between", value1, value2, "osName");
            return (Criteria) this;
        }

        public Criteria andOsVersionIsNull() {
            addCriterion("`os_version` is null");
            return (Criteria) this;
        }

        public Criteria andOsVersionIsNotNull() {
            addCriterion("`os_version` is not null");
            return (Criteria) this;
        }

        public Criteria andOsVersionEqualTo(String value) {
            addCriterion("`os_version` =", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotEqualTo(String value) {
            addCriterion("`os_version` <>", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionGreaterThan(String value) {
            addCriterion("`os_version` >", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionGreaterThanOrEqualTo(String value) {
            addCriterion("`os_version` >=", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLessThan(String value) {
            addCriterion("`os_version` <", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLessThanOrEqualTo(String value) {
            addCriterion("`os_version` <=", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionLike(String value) {
            addCriterion("`os_version` like", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotLike(String value) {
            addCriterion("`os_version` not like", value, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionIn(List<String> values) {
            addCriterion("`os_version` in", values, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotIn(List<String> values) {
            addCriterion("`os_version` not in", values, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionBetween(String value1, String value2) {
            addCriterion("`os_version` between", value1, value2, "osVersion");
            return (Criteria) this;
        }

        public Criteria andOsVersionNotBetween(String value1, String value2) {
            addCriterion("`os_version` not between", value1, value2, "osVersion");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressIsNull() {
            addCriterion("`ble_mac_address` is null");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressIsNotNull() {
            addCriterion("`ble_mac_address` is not null");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressEqualTo(String value) {
            addCriterion("`ble_mac_address` =", value, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressNotEqualTo(String value) {
            addCriterion("`ble_mac_address` <>", value, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressGreaterThan(String value) {
            addCriterion("`ble_mac_address` >", value, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressGreaterThanOrEqualTo(String value) {
            addCriterion("`ble_mac_address` >=", value, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressLessThan(String value) {
            addCriterion("`ble_mac_address` <", value, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressLessThanOrEqualTo(String value) {
            addCriterion("`ble_mac_address` <=", value, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressLike(String value) {
            addCriterion("`ble_mac_address` like", value, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressNotLike(String value) {
            addCriterion("`ble_mac_address` not like", value, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressIn(List<String> values) {
            addCriterion("`ble_mac_address` in", values, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressNotIn(List<String> values) {
            addCriterion("`ble_mac_address` not in", values, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressBetween(String value1, String value2) {
            addCriterion("`ble_mac_address` between", value1, value2, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andBleMacAddressNotBetween(String value1, String value2) {
            addCriterion("`ble_mac_address` not between", value1, value2, "bleMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressIsNull() {
            addCriterion("`lan_mac_address` is null");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressIsNotNull() {
            addCriterion("`lan_mac_address` is not null");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressEqualTo(String value) {
            addCriterion("`lan_mac_address` =", value, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressNotEqualTo(String value) {
            addCriterion("`lan_mac_address` <>", value, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressGreaterThan(String value) {
            addCriterion("`lan_mac_address` >", value, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressGreaterThanOrEqualTo(String value) {
            addCriterion("`lan_mac_address` >=", value, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressLessThan(String value) {
            addCriterion("`lan_mac_address` <", value, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressLessThanOrEqualTo(String value) {
            addCriterion("`lan_mac_address` <=", value, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressLike(String value) {
            addCriterion("`lan_mac_address` like", value, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressNotLike(String value) {
            addCriterion("`lan_mac_address` not like", value, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressIn(List<String> values) {
            addCriterion("`lan_mac_address` in", values, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressNotIn(List<String> values) {
            addCriterion("`lan_mac_address` not in", values, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressBetween(String value1, String value2) {
            addCriterion("`lan_mac_address` between", value1, value2, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andLanMacAddressNotBetween(String value1, String value2) {
            addCriterion("`lan_mac_address` not between", value1, value2, "lanMacAddress");
            return (Criteria) this;
        }

        public Criteria andPnpIdIsNull() {
            addCriterion("`pnp_id` is null");
            return (Criteria) this;
        }

        public Criteria andPnpIdIsNotNull() {
            addCriterion("`pnp_id` is not null");
            return (Criteria) this;
        }

        public Criteria andPnpIdEqualTo(String value) {
            addCriterion("`pnp_id` =", value, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdNotEqualTo(String value) {
            addCriterion("`pnp_id` <>", value, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdGreaterThan(String value) {
            addCriterion("`pnp_id` >", value, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdGreaterThanOrEqualTo(String value) {
            addCriterion("`pnp_id` >=", value, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdLessThan(String value) {
            addCriterion("`pnp_id` <", value, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdLessThanOrEqualTo(String value) {
            addCriterion("`pnp_id` <=", value, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdLike(String value) {
            addCriterion("`pnp_id` like", value, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdNotLike(String value) {
            addCriterion("`pnp_id` not like", value, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdIn(List<String> values) {
            addCriterion("`pnp_id` in", values, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdNotIn(List<String> values) {
            addCriterion("`pnp_id` not in", values, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdBetween(String value1, String value2) {
            addCriterion("`pnp_id` between", value1, value2, "pnpId");
            return (Criteria) this;
        }

        public Criteria andPnpIdNotBetween(String value1, String value2) {
            addCriterion("`pnp_id` not between", value1, value2, "pnpId");
            return (Criteria) this;
        }

        public Criteria andVendorIsNull() {
            addCriterion("`vendor` is null");
            return (Criteria) this;
        }

        public Criteria andVendorIsNotNull() {
            addCriterion("`vendor` is not null");
            return (Criteria) this;
        }

        public Criteria andVendorEqualTo(String value) {
            addCriterion("`vendor` =", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotEqualTo(String value) {
            addCriterion("`vendor` <>", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorGreaterThan(String value) {
            addCriterion("`vendor` >", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorGreaterThanOrEqualTo(String value) {
            addCriterion("`vendor` >=", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorLessThan(String value) {
            addCriterion("`vendor` <", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorLessThanOrEqualTo(String value) {
            addCriterion("`vendor` <=", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorLike(String value) {
            addCriterion("`vendor` like", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotLike(String value) {
            addCriterion("`vendor` not like", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorIn(List<String> values) {
            addCriterion("`vendor` in", values, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotIn(List<String> values) {
            addCriterion("`vendor` not in", values, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorBetween(String value1, String value2) {
            addCriterion("`vendor` between", value1, value2, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotBetween(String value1, String value2) {
            addCriterion("`vendor` not between", value1, value2, "vendor");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNull() {
            addCriterion("`manufacturer` is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNotNull() {
            addCriterion("`manufacturer` is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerEqualTo(String value) {
            addCriterion("`manufacturer` =", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotEqualTo(String value) {
            addCriterion("`manufacturer` <>", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThan(String value) {
            addCriterion("`manufacturer` >", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThanOrEqualTo(String value) {
            addCriterion("`manufacturer` >=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThan(String value) {
            addCriterion("`manufacturer` <", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThanOrEqualTo(String value) {
            addCriterion("`manufacturer` <=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLike(String value) {
            addCriterion("`manufacturer` like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotLike(String value) {
            addCriterion("`manufacturer` not like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerIn(List<String> values) {
            addCriterion("`manufacturer` in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotIn(List<String> values) {
            addCriterion("`manufacturer` not in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerBetween(String value1, String value2) {
            addCriterion("`manufacturer` between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotBetween(String value1, String value2) {
            addCriterion("`manufacturer` not between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andModelIsNull() {
            addCriterion("`model` is null");
            return (Criteria) this;
        }

        public Criteria andModelIsNotNull() {
            addCriterion("`model` is not null");
            return (Criteria) this;
        }

        public Criteria andModelEqualTo(String value) {
            addCriterion("`model` =", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotEqualTo(String value) {
            addCriterion("`model` <>", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThan(String value) {
            addCriterion("`model` >", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelGreaterThanOrEqualTo(String value) {
            addCriterion("`model` >=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThan(String value) {
            addCriterion("`model` <", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLessThanOrEqualTo(String value) {
            addCriterion("`model` <=", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelLike(String value) {
            addCriterion("`model` like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotLike(String value) {
            addCriterion("`model` not like", value, "model");
            return (Criteria) this;
        }

        public Criteria andModelIn(List<String> values) {
            addCriterion("`model` in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotIn(List<String> values) {
            addCriterion("`model` not in", values, "model");
            return (Criteria) this;
        }

        public Criteria andModelBetween(String value1, String value2) {
            addCriterion("`model` between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andModelNotBetween(String value1, String value2) {
            addCriterion("`model` not between", value1, value2, "model");
            return (Criteria) this;
        }

        public Criteria andSerialNoIsNull() {
            addCriterion("`serial_no` is null");
            return (Criteria) this;
        }

        public Criteria andSerialNoIsNotNull() {
            addCriterion("`serial_no` is not null");
            return (Criteria) this;
        }

        public Criteria andSerialNoEqualTo(String value) {
            addCriterion("`serial_no` =", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotEqualTo(String value) {
            addCriterion("`serial_no` <>", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoGreaterThan(String value) {
            addCriterion("`serial_no` >", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoGreaterThanOrEqualTo(String value) {
            addCriterion("`serial_no` >=", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLessThan(String value) {
            addCriterion("`serial_no` <", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLessThanOrEqualTo(String value) {
            addCriterion("`serial_no` <=", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoLike(String value) {
            addCriterion("`serial_no` like", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotLike(String value) {
            addCriterion("`serial_no` not like", value, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoIn(List<String> values) {
            addCriterion("`serial_no` in", values, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotIn(List<String> values) {
            addCriterion("`serial_no` not in", values, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoBetween(String value1, String value2) {
            addCriterion("`serial_no` between", value1, value2, "serialNo");
            return (Criteria) this;
        }

        public Criteria andSerialNoNotBetween(String value1, String value2) {
            addCriterion("`serial_no` not between", value1, value2, "serialNo");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidIsNull() {
            addCriterion("`device_uuid` is null");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidIsNotNull() {
            addCriterion("`device_uuid` is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidEqualTo(String value) {
            addCriterion("`device_uuid` =", value, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidNotEqualTo(String value) {
            addCriterion("`device_uuid` <>", value, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidGreaterThan(String value) {
            addCriterion("`device_uuid` >", value, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidGreaterThanOrEqualTo(String value) {
            addCriterion("`device_uuid` >=", value, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidLessThan(String value) {
            addCriterion("`device_uuid` <", value, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidLessThanOrEqualTo(String value) {
            addCriterion("`device_uuid` <=", value, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidLike(String value) {
            addCriterion("`device_uuid` like", value, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidNotLike(String value) {
            addCriterion("`device_uuid` not like", value, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidIn(List<String> values) {
            addCriterion("`device_uuid` in", values, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidNotIn(List<String> values) {
            addCriterion("`device_uuid` not in", values, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidBetween(String value1, String value2) {
            addCriterion("`device_uuid` between", value1, value2, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andDeviceUuidNotBetween(String value1, String value2) {
            addCriterion("`device_uuid` not between", value1, value2, "deviceUuid");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionIsNull() {
            addCriterion("`hardware_version` is null");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionIsNotNull() {
            addCriterion("`hardware_version` is not null");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionEqualTo(String value) {
            addCriterion("`hardware_version` =", value, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionNotEqualTo(String value) {
            addCriterion("`hardware_version` <>", value, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionGreaterThan(String value) {
            addCriterion("`hardware_version` >", value, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionGreaterThanOrEqualTo(String value) {
            addCriterion("`hardware_version` >=", value, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionLessThan(String value) {
            addCriterion("`hardware_version` <", value, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionLessThanOrEqualTo(String value) {
            addCriterion("`hardware_version` <=", value, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionLike(String value) {
            addCriterion("`hardware_version` like", value, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionNotLike(String value) {
            addCriterion("`hardware_version` not like", value, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionIn(List<String> values) {
            addCriterion("`hardware_version` in", values, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionNotIn(List<String> values) {
            addCriterion("`hardware_version` not in", values, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionBetween(String value1, String value2) {
            addCriterion("`hardware_version` between", value1, value2, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andHardwareVersionNotBetween(String value1, String value2) {
            addCriterion("`hardware_version` not between", value1, value2, "hardwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionIsNull() {
            addCriterion("`firmware_version` is null");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionIsNotNull() {
            addCriterion("`firmware_version` is not null");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionEqualTo(String value) {
            addCriterion("`firmware_version` =", value, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionNotEqualTo(String value) {
            addCriterion("`firmware_version` <>", value, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionGreaterThan(String value) {
            addCriterion("`firmware_version` >", value, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionGreaterThanOrEqualTo(String value) {
            addCriterion("`firmware_version` >=", value, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionLessThan(String value) {
            addCriterion("`firmware_version` <", value, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionLessThanOrEqualTo(String value) {
            addCriterion("`firmware_version` <=", value, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionLike(String value) {
            addCriterion("`firmware_version` like", value, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionNotLike(String value) {
            addCriterion("`firmware_version` not like", value, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionIn(List<String> values) {
            addCriterion("`firmware_version` in", values, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionNotIn(List<String> values) {
            addCriterion("`firmware_version` not in", values, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionBetween(String value1, String value2) {
            addCriterion("`firmware_version` between", value1, value2, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andFirmwareVersionNotBetween(String value1, String value2) {
            addCriterion("`firmware_version` not between", value1, value2, "firmwareVersion");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesIsNull() {
            addCriterion("`capabilities` is null");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesIsNotNull() {
            addCriterion("`capabilities` is not null");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesEqualTo(List value) {
            addCapabilitiesCriterion("`capabilities` =", value, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesNotEqualTo(List value) {
            addCapabilitiesCriterion("`capabilities` <>", value, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesGreaterThan(List value) {
            addCapabilitiesCriterion("`capabilities` >", value, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesGreaterThanOrEqualTo(List value) {
            addCapabilitiesCriterion("`capabilities` >=", value, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesLessThan(List value) {
            addCapabilitiesCriterion("`capabilities` <", value, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesLessThanOrEqualTo(List value) {
            addCapabilitiesCriterion("`capabilities` <=", value, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesLike(List value) {
            addCapabilitiesCriterion("`capabilities` like", value, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesNotLike(List value) {
            addCapabilitiesCriterion("`capabilities` not like", value, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesIn(List<List> values) {
            addCapabilitiesCriterion("`capabilities` in", values, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesNotIn(List<List> values) {
            addCapabilitiesCriterion("`capabilities` not in", values, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesBetween(List value1, List value2) {
            addCapabilitiesCriterion("`capabilities` between", value1, value2, "capabilities");
            return (Criteria) this;
        }

        public Criteria andCapabilitiesNotBetween(List value1, List value2) {
            addCapabilitiesCriterion("`capabilities` not between", value1, value2, "capabilities");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("`enabled` is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("`enabled` is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(boolean value) {
            addCriterion("`enabled` =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(boolean value) {
            addCriterion("`enabled` <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(boolean value) {
            addCriterion("`enabled` >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(boolean value) {
            addCriterion("`enabled` >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(boolean value) {
            addCriterion("`enabled` <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(boolean value) {
            addCriterion("`enabled` <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Boolean> values) {
            addCriterion("`enabled` in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Boolean> values) {
            addCriterion("`enabled` not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(boolean value1, boolean value2) {
            addCriterion("`enabled` between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(boolean value1, boolean value2) {
            addCriterion("`enabled` not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andDeletedDateIsNull() {
            addCriterion("`deleted_date` is null");
            return (Criteria) this;
        }

        public Criteria andDeletedDateIsNotNull() {
            addCriterion("`deleted_date` is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedDateEqualTo(Date value) {
            addCriterion("`deleted_date` =", value, "deletedDate");
            return (Criteria) this;
        }

        public Criteria andDeletedDateNotEqualTo(Date value) {
            addCriterion("`deleted_date` <>", value, "deletedDate");
            return (Criteria) this;
        }

        public Criteria andDeletedDateGreaterThan(Date value) {
            addCriterion("`deleted_date` >", value, "deletedDate");
            return (Criteria) this;
        }

        public Criteria andDeletedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`deleted_date` >=", value, "deletedDate");
            return (Criteria) this;
        }

        public Criteria andDeletedDateLessThan(Date value) {
            addCriterion("`deleted_date` <", value, "deletedDate");
            return (Criteria) this;
        }

        public Criteria andDeletedDateLessThanOrEqualTo(Date value) {
            addCriterion("`deleted_date` <=", value, "deletedDate");
            return (Criteria) this;
        }

        public Criteria andDeletedDateIn(List<Date> values) {
            addCriterion("`deleted_date` in", values, "deletedDate");
            return (Criteria) this;
        }

        public Criteria andDeletedDateNotIn(List<Date> values) {
            addCriterion("`deleted_date` not in", values, "deletedDate");
            return (Criteria) this;
        }

        public Criteria andDeletedDateBetween(Date value1, Date value2) {
            addCriterion("`deleted_date` between", value1, value2, "deletedDate");
            return (Criteria) this;
        }

        public Criteria andDeletedDateNotBetween(Date value1, Date value2) {
            addCriterion("`deleted_date` not between", value1, value2, "deletedDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("`created_date` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("`created_date` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("`created_date` =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("`created_date` <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("`created_date` >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`created_date` >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("`created_date` <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("`created_date` <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("`created_date` in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("`created_date` not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("`created_date` between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("`created_date` not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNull() {
            addCriterion("`updated_date` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNotNull() {
            addCriterion("`updated_date` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateEqualTo(Date value) {
            addCriterion("`updated_date` =", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotEqualTo(Date value) {
            addCriterion("`updated_date` <>", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThan(Date value) {
            addCriterion("`updated_date` >", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`updated_date` >=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThan(Date value) {
            addCriterion("`updated_date` <", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterion("`updated_date` <=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIn(List<Date> values) {
            addCriterion("`updated_date` in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotIn(List<Date> values) {
            addCriterion("`updated_date` not in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateBetween(Date value1, Date value2) {
            addCriterion("`updated_date` between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterion("`updated_date` not between", value1, value2, "updatedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__device
     *
     * @mbg.generated do_not_delete_during_merge Sat May 19 06:25:18 EDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__device
     *
     * @mbg.generated Sat May 19 06:25:18 EDT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}