package com.bryllyant.kona.app.entity;

import com.bryllyant.kona.app.entity.BaseDevice.Type;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Device extends BaseDevice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.uid
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.type
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private Type type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.parent_id
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.advertiser_id
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String advertiserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.limit_ad_tracking_enabled
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private boolean limitAdTrackingEnabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.os_name
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String osName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.os_version
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String osVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.ble_mac_address
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String bleMacAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.lan_mac_address
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String lanMacAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.pnp_id
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String pnpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.vendor
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String vendor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.manufacturer
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.model
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.serial_no
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String serialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.device_uuid
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String deviceUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.hardware_version
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String hardwareVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.firmware_version
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private String firmwareVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.capabilities
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private List capabilities;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.enabled
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.deleted_date
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private Date deletedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.created_date
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__device.updated_date
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__device
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.uid
     *
     * @return the value of kona__device.uid
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.uid
     *
     * @param uid the value for kona__device.uid
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.type
     *
     * @return the value of kona__device.type
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public Type getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.type
     *
     * @param type the value for kona__device.type
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setType(Type type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.parent_id
     *
     * @return the value of kona__device.parent_id
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.parent_id
     *
     * @param parentId the value for kona__device.parent_id
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.advertiser_id
     *
     * @return the value of kona__device.advertiser_id
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getAdvertiserId() {
        return advertiserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.advertiser_id
     *
     * @param advertiserId the value for kona__device.advertiser_id
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setAdvertiserId(String advertiserId) {
        this.advertiserId = advertiserId == null ? null : advertiserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.limit_ad_tracking_enabled
     *
     * @return the value of kona__device.limit_ad_tracking_enabled
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public boolean isLimitAdTrackingEnabled() {
        return limitAdTrackingEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.limit_ad_tracking_enabled
     *
     * @param limitAdTrackingEnabled the value for kona__device.limit_ad_tracking_enabled
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setLimitAdTrackingEnabled(boolean limitAdTrackingEnabled) {
        this.limitAdTrackingEnabled = limitAdTrackingEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.os_name
     *
     * @return the value of kona__device.os_name
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getOsName() {
        return osName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.os_name
     *
     * @param osName the value for kona__device.os_name
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setOsName(String osName) {
        this.osName = osName == null ? null : osName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.os_version
     *
     * @return the value of kona__device.os_version
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.os_version
     *
     * @param osVersion the value for kona__device.os_version
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion == null ? null : osVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.ble_mac_address
     *
     * @return the value of kona__device.ble_mac_address
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getBleMacAddress() {
        return bleMacAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.ble_mac_address
     *
     * @param bleMacAddress the value for kona__device.ble_mac_address
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setBleMacAddress(String bleMacAddress) {
        this.bleMacAddress = bleMacAddress == null ? null : bleMacAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.lan_mac_address
     *
     * @return the value of kona__device.lan_mac_address
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getLanMacAddress() {
        return lanMacAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.lan_mac_address
     *
     * @param lanMacAddress the value for kona__device.lan_mac_address
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setLanMacAddress(String lanMacAddress) {
        this.lanMacAddress = lanMacAddress == null ? null : lanMacAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.pnp_id
     *
     * @return the value of kona__device.pnp_id
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getPnpId() {
        return pnpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.pnp_id
     *
     * @param pnpId the value for kona__device.pnp_id
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setPnpId(String pnpId) {
        this.pnpId = pnpId == null ? null : pnpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.vendor
     *
     * @return the value of kona__device.vendor
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.vendor
     *
     * @param vendor the value for kona__device.vendor
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setVendor(String vendor) {
        this.vendor = vendor == null ? null : vendor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.manufacturer
     *
     * @return the value of kona__device.manufacturer
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.manufacturer
     *
     * @param manufacturer the value for kona__device.manufacturer
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.model
     *
     * @return the value of kona__device.model
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.model
     *
     * @param model the value for kona__device.model
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.serial_no
     *
     * @return the value of kona__device.serial_no
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.serial_no
     *
     * @param serialNo the value for kona__device.serial_no
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.device_uuid
     *
     * @return the value of kona__device.device_uuid
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getDeviceUuid() {
        return deviceUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.device_uuid
     *
     * @param deviceUuid the value for kona__device.device_uuid
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setDeviceUuid(String deviceUuid) {
        this.deviceUuid = deviceUuid == null ? null : deviceUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.hardware_version
     *
     * @return the value of kona__device.hardware_version
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getHardwareVersion() {
        return hardwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.hardware_version
     *
     * @param hardwareVersion the value for kona__device.hardware_version
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setHardwareVersion(String hardwareVersion) {
        this.hardwareVersion = hardwareVersion == null ? null : hardwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.firmware_version
     *
     * @return the value of kona__device.firmware_version
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public String getFirmwareVersion() {
        return firmwareVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.firmware_version
     *
     * @param firmwareVersion the value for kona__device.firmware_version
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setFirmwareVersion(String firmwareVersion) {
        this.firmwareVersion = firmwareVersion == null ? null : firmwareVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.capabilities
     *
     * @return the value of kona__device.capabilities
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public List getCapabilities() {
        return capabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.capabilities
     *
     * @param capabilities the value for kona__device.capabilities
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setCapabilities(List capabilities) {
        this.capabilities = capabilities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.enabled
     *
     * @return the value of kona__device.enabled
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.enabled
     *
     * @param enabled the value for kona__device.enabled
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.deleted_date
     *
     * @return the value of kona__device.deleted_date
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public Date getDeletedDate() {
        return deletedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.deleted_date
     *
     * @param deletedDate the value for kona__device.deleted_date
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setDeletedDate(Date deletedDate) {
        this.deletedDate = deletedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.created_date
     *
     * @return the value of kona__device.created_date
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.created_date
     *
     * @param createdDate the value for kona__device.created_date
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__device.updated_date
     *
     * @return the value of kona__device.updated_date
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__device.updated_date
     *
     * @param updatedDate the value for kona__device.updated_date
     *
     * @mbg.generated Mon May 28 09:46:31 EDT 2018
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}