package com.bryllyant.kona.app.entity;

import com.bryllyant.kona.app.entity.KFile.Access;
import com.bryllyant.kona.app.entity.KFile.Type;
import java.io.Serializable;

public class File extends KBaseFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__file.type
     *
     * @mbg.generated Tue Mar 06 18:09:25 EST 2018
     */
    private Type type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__file.access
     *
     * @mbg.generated Tue Mar 06 18:09:25 EST 2018
     */
    private Access access;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__file
     *
     * @mbg.generated Tue Mar 06 18:09:25 EST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__file.type
     *
     * @return the value of kona__file.type
     *
     * @mbg.generated Tue Mar 06 18:09:25 EST 2018
     */
    public Type getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__file.type
     *
     * @param type the value for kona__file.type
     *
     * @mbg.generated Tue Mar 06 18:09:25 EST 2018
     */
    public void setType(Type type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__file.access
     *
     * @return the value of kona__file.access
     *
     * @mbg.generated Tue Mar 06 18:09:25 EST 2018
     */
    public Access getAccess() {
        return access;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__file.access
     *
     * @param access the value for kona__file.access
     *
     * @mbg.generated Tue Mar 06 18:09:25 EST 2018
     */
    public void setAccess(Access access) {
        this.access = access;
    }
}