package com.bryllyant.kona.app.entity;

import java.io.Serializable;

public class FriendshipEvent extends KBaseFriendshipEvent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__friendship_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    private static final long serialVersionUID = 1L;
}