package com.bryllyant.kona.app.entity;

import java.io.Serializable;

public class Partner extends KBasePartner implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__partner
     *
     * @mbg.generated Tue Mar 06 18:09:25 EST 2018
     */
    private static final long serialVersionUID = 1L;
}