package com.bryllyant.kona.app.entity;

import com.bryllyant.kona.data.entity.KBaseEntity;
import java.io.Serializable;
import java.util.Date;

public class PlaceTag extends KBaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__place_tag.uid
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__place_tag.place_id
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    private Long placeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__place_tag.slug
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    private String slug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__place_tag.tag
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__place_tag.created_date
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__place_tag.updated_date
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__place_tag
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__place_tag.uid
     *
     * @return the value of kona__place_tag.uid
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__place_tag.uid
     *
     * @param uid the value for kona__place_tag.uid
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__place_tag.place_id
     *
     * @return the value of kona__place_tag.place_id
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public Long getPlaceId() {
        return placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__place_tag.place_id
     *
     * @param placeId the value for kona__place_tag.place_id
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public void setPlaceId(Long placeId) {
        this.placeId = placeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__place_tag.slug
     *
     * @return the value of kona__place_tag.slug
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__place_tag.slug
     *
     * @param slug the value for kona__place_tag.slug
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__place_tag.tag
     *
     * @return the value of kona__place_tag.tag
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__place_tag.tag
     *
     * @param tag the value for kona__place_tag.tag
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__place_tag.created_date
     *
     * @return the value of kona__place_tag.created_date
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__place_tag.created_date
     *
     * @param createdDate the value for kona__place_tag.created_date
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__place_tag.updated_date
     *
     * @return the value of kona__place_tag.updated_date
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__place_tag.updated_date
     *
     * @param updatedDate the value for kona__place_tag.updated_date
     *
     * @mbg.generated Fri Apr 06 16:41:59 EDT 2018
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}