package com.bryllyant.kona.app.entity;

import java.io.Serializable;

public class Place extends KBasePlace implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__place
     *
     * @mbg.generated Sat Mar 24 14:14:45 EDT 2018
     */
    private static final long serialVersionUID = 1L;
}