package com.bryllyant.kona.app.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

public class ProductSkuExample implements com.bryllyant.kona.data.mybatis.KEntityExample<ProductSkuExample.Criteria> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private Integer limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated
     */
    private String fts;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public ProductSkuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public Integer getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public void setFts(String fts) {
        this.fts = fts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated
     */
    public String getFts() {
        return fts;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> variantsCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            variantsCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getVariantsCriteria() {
            return variantsCriteria;
        }

        protected void addVariantsCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            variantsCriteria.add(new Criterion(condition, value, "com.bryllyant.kona.data.mybatis.KMapHandler"));
            allCriteria = null;
        }

        protected void addVariantsCriterion(String condition, Map value1, Map value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            variantsCriteria.add(new Criterion(condition, value1, value2, "com.bryllyant.kona.data.mybatis.KMapHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || variantsCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(variantsCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("`uid` is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("`uid` is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("`uid` =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("`uid` <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("`uid` >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("`uid` >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("`uid` <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("`uid` <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("`uid` like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("`uid` not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("`uid` in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("`uid` not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("`uid` between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("`uid` not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("`product_id` is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("`product_id` is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Long value) {
            addCriterion("`product_id` =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Long value) {
            addCriterion("`product_id` <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Long value) {
            addCriterion("`product_id` >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`product_id` >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Long value) {
            addCriterion("`product_id` <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Long value) {
            addCriterion("`product_id` <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Long> values) {
            addCriterion("`product_id` in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Long> values) {
            addCriterion("`product_id` not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Long value1, Long value2) {
            addCriterion("`product_id` between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Long value1, Long value2) {
            addCriterion("`product_id` not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSkuIsNull() {
            addCriterion("`sku` is null");
            return (Criteria) this;
        }

        public Criteria andSkuIsNotNull() {
            addCriterion("`sku` is not null");
            return (Criteria) this;
        }

        public Criteria andSkuEqualTo(String value) {
            addCriterion("`sku` =", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotEqualTo(String value) {
            addCriterion("`sku` <>", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuGreaterThan(String value) {
            addCriterion("`sku` >", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuGreaterThanOrEqualTo(String value) {
            addCriterion("`sku` >=", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLessThan(String value) {
            addCriterion("`sku` <", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLessThanOrEqualTo(String value) {
            addCriterion("`sku` <=", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLike(String value) {
            addCriterion("`sku` like", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotLike(String value) {
            addCriterion("`sku` not like", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuIn(List<String> values) {
            addCriterion("`sku` in", values, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotIn(List<String> values) {
            addCriterion("`sku` not in", values, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuBetween(String value1, String value2) {
            addCriterion("`sku` between", value1, value2, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotBetween(String value1, String value2) {
            addCriterion("`sku` not between", value1, value2, "sku");
            return (Criteria) this;
        }

        public Criteria andVariantsIsNull() {
            addCriterion("`variants` is null");
            return (Criteria) this;
        }

        public Criteria andVariantsIsNotNull() {
            addCriterion("`variants` is not null");
            return (Criteria) this;
        }

        public Criteria andVariantsEqualTo(Map value) {
            addVariantsCriterion("`variants` =", value, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsNotEqualTo(Map value) {
            addVariantsCriterion("`variants` <>", value, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsGreaterThan(Map value) {
            addVariantsCriterion("`variants` >", value, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsGreaterThanOrEqualTo(Map value) {
            addVariantsCriterion("`variants` >=", value, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsLessThan(Map value) {
            addVariantsCriterion("`variants` <", value, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsLessThanOrEqualTo(Map value) {
            addVariantsCriterion("`variants` <=", value, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsLike(Map value) {
            addVariantsCriterion("`variants` like", value, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsNotLike(Map value) {
            addVariantsCriterion("`variants` not like", value, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsIn(List<Map> values) {
            addVariantsCriterion("`variants` in", values, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsNotIn(List<Map> values) {
            addVariantsCriterion("`variants` not in", values, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsBetween(Map value1, Map value2) {
            addVariantsCriterion("`variants` between", value1, value2, "variants");
            return (Criteria) this;
        }

        public Criteria andVariantsNotBetween(Map value1, Map value2) {
            addVariantsCriterion("`variants` not between", value1, value2, "variants");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("`description` is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("`description` is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("`description` =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("`description` <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("`description` >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("`description` >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("`description` <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("`description` <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("`description` like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("`description` not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("`description` in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("`description` not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("`description` between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("`description` not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderIsNull() {
            addCriterion("`display_order` is null");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderIsNotNull() {
            addCriterion("`display_order` is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderEqualTo(Integer value) {
            addCriterion("`display_order` =", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNotEqualTo(Integer value) {
            addCriterion("`display_order` <>", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderGreaterThan(Integer value) {
            addCriterion("`display_order` >", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("`display_order` >=", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderLessThan(Integer value) {
            addCriterion("`display_order` <", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderLessThanOrEqualTo(Integer value) {
            addCriterion("`display_order` <=", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderIn(List<Integer> values) {
            addCriterion("`display_order` in", values, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNotIn(List<Integer> values) {
            addCriterion("`display_order` not in", values, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderBetween(Integer value1, Integer value2) {
            addCriterion("`display_order` between", value1, value2, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("`display_order` not between", value1, value2, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("`price` is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("`price` is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("`price` =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("`price` <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("`price` >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`price` >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("`price` <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`price` <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("`price` in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("`price` not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`price` between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`price` not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andSetupFeeIsNull() {
            addCriterion("`setup_fee` is null");
            return (Criteria) this;
        }

        public Criteria andSetupFeeIsNotNull() {
            addCriterion("`setup_fee` is not null");
            return (Criteria) this;
        }

        public Criteria andSetupFeeEqualTo(BigDecimal value) {
            addCriterion("`setup_fee` =", value, "setupFee");
            return (Criteria) this;
        }

        public Criteria andSetupFeeNotEqualTo(BigDecimal value) {
            addCriterion("`setup_fee` <>", value, "setupFee");
            return (Criteria) this;
        }

        public Criteria andSetupFeeGreaterThan(BigDecimal value) {
            addCriterion("`setup_fee` >", value, "setupFee");
            return (Criteria) this;
        }

        public Criteria andSetupFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`setup_fee` >=", value, "setupFee");
            return (Criteria) this;
        }

        public Criteria andSetupFeeLessThan(BigDecimal value) {
            addCriterion("`setup_fee` <", value, "setupFee");
            return (Criteria) this;
        }

        public Criteria andSetupFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`setup_fee` <=", value, "setupFee");
            return (Criteria) this;
        }

        public Criteria andSetupFeeIn(List<BigDecimal> values) {
            addCriterion("`setup_fee` in", values, "setupFee");
            return (Criteria) this;
        }

        public Criteria andSetupFeeNotIn(List<BigDecimal> values) {
            addCriterion("`setup_fee` not in", values, "setupFee");
            return (Criteria) this;
        }

        public Criteria andSetupFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`setup_fee` between", value1, value2, "setupFee");
            return (Criteria) this;
        }

        public Criteria andSetupFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`setup_fee` not between", value1, value2, "setupFee");
            return (Criteria) this;
        }

        public Criteria andTrialDaysIsNull() {
            addCriterion("`trial_days` is null");
            return (Criteria) this;
        }

        public Criteria andTrialDaysIsNotNull() {
            addCriterion("`trial_days` is not null");
            return (Criteria) this;
        }

        public Criteria andTrialDaysEqualTo(Integer value) {
            addCriterion("`trial_days` =", value, "trialDays");
            return (Criteria) this;
        }

        public Criteria andTrialDaysNotEqualTo(Integer value) {
            addCriterion("`trial_days` <>", value, "trialDays");
            return (Criteria) this;
        }

        public Criteria andTrialDaysGreaterThan(Integer value) {
            addCriterion("`trial_days` >", value, "trialDays");
            return (Criteria) this;
        }

        public Criteria andTrialDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("`trial_days` >=", value, "trialDays");
            return (Criteria) this;
        }

        public Criteria andTrialDaysLessThan(Integer value) {
            addCriterion("`trial_days` <", value, "trialDays");
            return (Criteria) this;
        }

        public Criteria andTrialDaysLessThanOrEqualTo(Integer value) {
            addCriterion("`trial_days` <=", value, "trialDays");
            return (Criteria) this;
        }

        public Criteria andTrialDaysIn(List<Integer> values) {
            addCriterion("`trial_days` in", values, "trialDays");
            return (Criteria) this;
        }

        public Criteria andTrialDaysNotIn(List<Integer> values) {
            addCriterion("`trial_days` not in", values, "trialDays");
            return (Criteria) this;
        }

        public Criteria andTrialDaysBetween(Integer value1, Integer value2) {
            addCriterion("`trial_days` between", value1, value2, "trialDays");
            return (Criteria) this;
        }

        public Criteria andTrialDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("`trial_days` not between", value1, value2, "trialDays");
            return (Criteria) this;
        }

        public Criteria andSubscriptionIsNull() {
            addCriterion("`subscription` is null");
            return (Criteria) this;
        }

        public Criteria andSubscriptionIsNotNull() {
            addCriterion("`subscription` is not null");
            return (Criteria) this;
        }

        public Criteria andSubscriptionEqualTo(boolean value) {
            addCriterion("`subscription` =", value, "subscription");
            return (Criteria) this;
        }

        public Criteria andSubscriptionNotEqualTo(boolean value) {
            addCriterion("`subscription` <>", value, "subscription");
            return (Criteria) this;
        }

        public Criteria andSubscriptionGreaterThan(boolean value) {
            addCriterion("`subscription` >", value, "subscription");
            return (Criteria) this;
        }

        public Criteria andSubscriptionGreaterThanOrEqualTo(boolean value) {
            addCriterion("`subscription` >=", value, "subscription");
            return (Criteria) this;
        }

        public Criteria andSubscriptionLessThan(boolean value) {
            addCriterion("`subscription` <", value, "subscription");
            return (Criteria) this;
        }

        public Criteria andSubscriptionLessThanOrEqualTo(boolean value) {
            addCriterion("`subscription` <=", value, "subscription");
            return (Criteria) this;
        }

        public Criteria andSubscriptionIn(List<Boolean> values) {
            addCriterion("`subscription` in", values, "subscription");
            return (Criteria) this;
        }

        public Criteria andSubscriptionNotIn(List<Boolean> values) {
            addCriterion("`subscription` not in", values, "subscription");
            return (Criteria) this;
        }

        public Criteria andSubscriptionBetween(boolean value1, boolean value2) {
            addCriterion("`subscription` between", value1, value2, "subscription");
            return (Criteria) this;
        }

        public Criteria andSubscriptionNotBetween(boolean value1, boolean value2) {
            addCriterion("`subscription` not between", value1, value2, "subscription");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysIsNull() {
            addCriterion("`subscription_days` is null");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysIsNotNull() {
            addCriterion("`subscription_days` is not null");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysEqualTo(Integer value) {
            addCriterion("`subscription_days` =", value, "subscriptionDays");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysNotEqualTo(Integer value) {
            addCriterion("`subscription_days` <>", value, "subscriptionDays");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysGreaterThan(Integer value) {
            addCriterion("`subscription_days` >", value, "subscriptionDays");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("`subscription_days` >=", value, "subscriptionDays");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysLessThan(Integer value) {
            addCriterion("`subscription_days` <", value, "subscriptionDays");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysLessThanOrEqualTo(Integer value) {
            addCriterion("`subscription_days` <=", value, "subscriptionDays");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysIn(List<Integer> values) {
            addCriterion("`subscription_days` in", values, "subscriptionDays");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysNotIn(List<Integer> values) {
            addCriterion("`subscription_days` not in", values, "subscriptionDays");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysBetween(Integer value1, Integer value2) {
            addCriterion("`subscription_days` between", value1, value2, "subscriptionDays");
            return (Criteria) this;
        }

        public Criteria andSubscriptionDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("`subscription_days` not between", value1, value2, "subscriptionDays");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("`enabled` is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("`enabled` is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(boolean value) {
            addCriterion("`enabled` =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(boolean value) {
            addCriterion("`enabled` <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(boolean value) {
            addCriterion("`enabled` >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(boolean value) {
            addCriterion("`enabled` >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(boolean value) {
            addCriterion("`enabled` <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(boolean value) {
            addCriterion("`enabled` <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Boolean> values) {
            addCriterion("`enabled` in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Boolean> values) {
            addCriterion("`enabled` not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(boolean value1, boolean value2) {
            addCriterion("`enabled` between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(boolean value1, boolean value2) {
            addCriterion("`enabled` not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("`created_date` is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("`created_date` is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("`created_date` =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("`created_date` <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("`created_date` >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`created_date` >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("`created_date` <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("`created_date` <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("`created_date` in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("`created_date` not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("`created_date` between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("`created_date` not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNull() {
            addCriterion("`updated_date` is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIsNotNull() {
            addCriterion("`updated_date` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateEqualTo(Date value) {
            addCriterion("`updated_date` =", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotEqualTo(Date value) {
            addCriterion("`updated_date` <>", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThan(Date value) {
            addCriterion("`updated_date` >", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("`updated_date` >=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThan(Date value) {
            addCriterion("`updated_date` <", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterion("`updated_date` <=", value, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateIn(List<Date> values) {
            addCriterion("`updated_date` in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotIn(List<Date> values) {
            addCriterion("`updated_date` not in", values, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateBetween(Date value1, Date value2) {
            addCriterion("`updated_date` between", value1, value2, "updatedDate");
            return (Criteria) this;
        }

        public Criteria andUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterion("`updated_date` not between", value1, value2, "updatedDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__product_sku
     *
     * @mbg.generated do_not_delete_during_merge Sat May 12 06:10:33 EDT 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kona__product_sku
     *
     * @mbg.generated Sat May 12 06:10:33 EDT 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}