package com.bryllyant.kona.app.entity;

import com.bryllyant.kona.data.entity.KBaseEntity;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Map;

public class ProductSku extends KBaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.uid
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.product_id
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.name
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.sku
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private String sku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.variants
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private Map variants;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.description
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.display_order
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.price
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.setup_fee
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private BigDecimal setupFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.trial_days
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private Integer trialDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.subscription
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private boolean subscription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.subscription_days
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private Integer subscriptionDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.enabled
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.created_date
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__product_sku.updated_date
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__product_sku
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.uid
     *
     * @return the value of kona__product_sku.uid
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.uid
     *
     * @param uid the value for kona__product_sku.uid
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.product_id
     *
     * @return the value of kona__product_sku.product_id
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.product_id
     *
     * @param productId the value for kona__product_sku.product_id
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.name
     *
     * @return the value of kona__product_sku.name
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.name
     *
     * @param name the value for kona__product_sku.name
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.sku
     *
     * @return the value of kona__product_sku.sku
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.sku
     *
     * @param sku the value for kona__product_sku.sku
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.variants
     *
     * @return the value of kona__product_sku.variants
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public Map getVariants() {
        return variants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.variants
     *
     * @param variants the value for kona__product_sku.variants
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setVariants(Map variants) {
        this.variants = variants;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.description
     *
     * @return the value of kona__product_sku.description
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.description
     *
     * @param description the value for kona__product_sku.description
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.display_order
     *
     * @return the value of kona__product_sku.display_order
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.display_order
     *
     * @param displayOrder the value for kona__product_sku.display_order
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.price
     *
     * @return the value of kona__product_sku.price
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.price
     *
     * @param price the value for kona__product_sku.price
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.setup_fee
     *
     * @return the value of kona__product_sku.setup_fee
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public BigDecimal getSetupFee() {
        return setupFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.setup_fee
     *
     * @param setupFee the value for kona__product_sku.setup_fee
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setSetupFee(BigDecimal setupFee) {
        this.setupFee = setupFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.trial_days
     *
     * @return the value of kona__product_sku.trial_days
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public Integer getTrialDays() {
        return trialDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.trial_days
     *
     * @param trialDays the value for kona__product_sku.trial_days
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setTrialDays(Integer trialDays) {
        this.trialDays = trialDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.subscription
     *
     * @return the value of kona__product_sku.subscription
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public boolean isSubscription() {
        return subscription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.subscription
     *
     * @param subscription the value for kona__product_sku.subscription
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setSubscription(boolean subscription) {
        this.subscription = subscription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.subscription_days
     *
     * @return the value of kona__product_sku.subscription_days
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public Integer getSubscriptionDays() {
        return subscriptionDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.subscription_days
     *
     * @param subscriptionDays the value for kona__product_sku.subscription_days
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setSubscriptionDays(Integer subscriptionDays) {
        this.subscriptionDays = subscriptionDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.enabled
     *
     * @return the value of kona__product_sku.enabled
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.enabled
     *
     * @param enabled the value for kona__product_sku.enabled
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.created_date
     *
     * @return the value of kona__product_sku.created_date
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.created_date
     *
     * @param createdDate the value for kona__product_sku.created_date
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__product_sku.updated_date
     *
     * @return the value of kona__product_sku.updated_date
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__product_sku.updated_date
     *
     * @param updatedDate the value for kona__product_sku.updated_date
     *
     * @mbg.generated Wed Apr 11 12:22:58 EDT 2018
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}