package com.bryllyant.kona.app.entity;

import com.bryllyant.kona.app.entity.BasePayment.Type;
import com.bryllyant.kona.data.entity.KBaseEntity;
import java.io.Serializable;
import java.util.Date;

public class Purchase extends KBaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.uid
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.parent_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.account_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Long accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.user_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.product_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.product_sku_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Long productSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.promo_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Long promoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.partner_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Long partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.campaign_channel_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Long campaignChannelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.invoice_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Long invoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.payment_type
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Type paymentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.kind
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private String kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.quantity
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.auto_renew
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private boolean autoRenew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.enabled
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.expiration_date
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Date expirationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.created_date
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kona__purchase.updated_date
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__purchase
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.uid
     *
     * @return the value of kona__purchase.uid
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.uid
     *
     * @param uid the value for kona__purchase.uid
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.parent_id
     *
     * @return the value of kona__purchase.parent_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.parent_id
     *
     * @param parentId the value for kona__purchase.parent_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.account_id
     *
     * @return the value of kona__purchase.account_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.account_id
     *
     * @param accountId the value for kona__purchase.account_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.user_id
     *
     * @return the value of kona__purchase.user_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.user_id
     *
     * @param userId the value for kona__purchase.user_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.product_id
     *
     * @return the value of kona__purchase.product_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.product_id
     *
     * @param productId the value for kona__purchase.product_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.product_sku_id
     *
     * @return the value of kona__purchase.product_sku_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Long getProductSkuId() {
        return productSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.product_sku_id
     *
     * @param productSkuId the value for kona__purchase.product_sku_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setProductSkuId(Long productSkuId) {
        this.productSkuId = productSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.promo_id
     *
     * @return the value of kona__purchase.promo_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Long getPromoId() {
        return promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.promo_id
     *
     * @param promoId the value for kona__purchase.promo_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setPromoId(Long promoId) {
        this.promoId = promoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.partner_id
     *
     * @return the value of kona__purchase.partner_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Long getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.partner_id
     *
     * @param partnerId the value for kona__purchase.partner_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setPartnerId(Long partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.campaign_channel_id
     *
     * @return the value of kona__purchase.campaign_channel_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Long getCampaignChannelId() {
        return campaignChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.campaign_channel_id
     *
     * @param campaignChannelId the value for kona__purchase.campaign_channel_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setCampaignChannelId(Long campaignChannelId) {
        this.campaignChannelId = campaignChannelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.invoice_id
     *
     * @return the value of kona__purchase.invoice_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Long getInvoiceId() {
        return invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.invoice_id
     *
     * @param invoiceId the value for kona__purchase.invoice_id
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setInvoiceId(Long invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.payment_type
     *
     * @return the value of kona__purchase.payment_type
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Type getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.payment_type
     *
     * @param paymentType the value for kona__purchase.payment_type
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setPaymentType(Type paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.kind
     *
     * @return the value of kona__purchase.kind
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.kind
     *
     * @param kind the value for kona__purchase.kind
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.quantity
     *
     * @return the value of kona__purchase.quantity
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.quantity
     *
     * @param quantity the value for kona__purchase.quantity
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.auto_renew
     *
     * @return the value of kona__purchase.auto_renew
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public boolean isAutoRenew() {
        return autoRenew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.auto_renew
     *
     * @param autoRenew the value for kona__purchase.auto_renew
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setAutoRenew(boolean autoRenew) {
        this.autoRenew = autoRenew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.enabled
     *
     * @return the value of kona__purchase.enabled
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.enabled
     *
     * @param enabled the value for kona__purchase.enabled
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.expiration_date
     *
     * @return the value of kona__purchase.expiration_date
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Date getExpirationDate() {
        return expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.expiration_date
     *
     * @param expirationDate the value for kona__purchase.expiration_date
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.created_date
     *
     * @return the value of kona__purchase.created_date
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.created_date
     *
     * @param createdDate the value for kona__purchase.created_date
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kona__purchase.updated_date
     *
     * @return the value of kona__purchase.updated_date
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kona__purchase.updated_date
     *
     * @param updatedDate the value for kona__purchase.updated_date
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}