package com.bryllyant.kona.app.entity;

import java.io.Serializable;

public class RemoteService extends KBaseRemoteService implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__remote_service
     *
     * @mbg.generated Sat Mar 17 14:03:15 EDT 2018
     */
    private static final long serialVersionUID = 1L;
}