package com.bryllyant.kona.app.entity;

import java.io.Serializable;

public class ShortUrl extends KBaseShortUrl implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kona__short_url
     *
     * @mbg.generated Thu Mar 08 08:48:59 EST 2018
     */
    private static final long serialVersionUID = 1L;
}