package com.bryllyant.kona.app.dao;
import java.util.Date;

import com.bryllyant.kona.app.entity.AnalyticsEvent;
import com.bryllyant.kona.app.entity.AnalyticsEventExample;
import com.bryllyant.kona.data.dao.KMyBatisMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnalyticsEventMapper extends com.bryllyant.kona.data.dao.KMyBatisMapper<AnalyticsEvent, AnalyticsEventExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    long countByExample(AnalyticsEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    int deleteByExample(AnalyticsEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    int insert(AnalyticsEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    int insertSelective(AnalyticsEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    List<AnalyticsEvent> selectByExample(AnalyticsEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    AnalyticsEvent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    int updateByExampleSelective(@Param("record") AnalyticsEvent record, @Param("example") AnalyticsEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    int updateByExample(@Param("record") AnalyticsEvent record, @Param("example") AnalyticsEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    int updateByPrimaryKeySelective(AnalyticsEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__analytics_event
     *
     * @mbg.generated Mon Mar 12 17:32:51 EDT 2018
     */
    int updateByPrimaryKey(AnalyticsEvent record);

    int updateCoords(Long objectId);

    List<AnalyticsEvent> selectProximate(
        @Param("latitude") Double latitude,
        @Param("longitude") Double longitude, 
        @Param("radius") Double radius,
        @Param("startDate") Date startDate,
        @Param("endDate") Date endDate,
        @Param("objectIds") List<Long> objectIdList
    );
}           
