package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.App;
import com.bryllyant.kona.app.entity.AppExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    long countByExample(AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int deleteByExample(AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int insert(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int insertSelective(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    List<App> selectByExample(AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    App selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByExampleSelective(@Param("record") App record, @Param("example") AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByExample(@Param("record") App record, @Param("example") AppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByPrimaryKeySelective(App record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__app
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByPrimaryKey(App record);
}