package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.AuthCode;
import com.bryllyant.kona.app.entity.AuthCodeExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AuthCodeMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    long countByExample(AuthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int deleteByExample(AuthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int insert(AuthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int insertSelective(AuthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    List<AuthCode> selectByExample(AuthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    AuthCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByExampleSelective(@Param("record") AuthCode record, @Param("example") AuthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByExample(@Param("record") AuthCode record, @Param("example") AuthCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByPrimaryKeySelective(AuthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__auth_code
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByPrimaryKey(AuthCode record);
}