package com.bryllyant.kona.app.dao;
import java.util.Date;

import com.bryllyant.kona.app.entity.CampaignEvent;
import com.bryllyant.kona.app.entity.CampaignEventExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CampaignEventMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    long countByExample(CampaignEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int deleteByExample(CampaignEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int insert(CampaignEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int insertSelective(CampaignEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    List<CampaignEvent> selectByExample(CampaignEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    CampaignEvent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByExampleSelective(@Param("record") CampaignEvent record, @Param("example") CampaignEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByExample(@Param("record") CampaignEvent record, @Param("example") CampaignEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByPrimaryKeySelective(CampaignEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_event
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByPrimaryKey(CampaignEvent record);

    int updateCoords(Long objectId);

    List<CampaignEvent> selectProximate(
        @Param("latitude") Double latitude,
        @Param("longitude") Double longitude, 
        @Param("radius") Double radius,
        @Param("startDate") Date startDate,
        @Param("endDate") Date endDate
    );
}           
