package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.CampaignReplyMessage;
import com.bryllyant.kona.app.entity.CampaignReplyMessageExample;
import com.bryllyant.kona.data.dao.KMyBatisMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CampaignReplyMessageMapper extends com.bryllyant.kona.data.dao.KMyBatisMapper<CampaignReplyMessage, CampaignReplyMessageExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    long countByExample(CampaignReplyMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    int deleteByExample(CampaignReplyMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    int insert(CampaignReplyMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    int insertSelective(CampaignReplyMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    List<CampaignReplyMessage> selectByExample(CampaignReplyMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    CampaignReplyMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    int updateByExampleSelective(@Param("record") CampaignReplyMessage record, @Param("example") CampaignReplyMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    int updateByExample(@Param("record") CampaignReplyMessage record, @Param("example") CampaignReplyMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    int updateByPrimaryKeySelective(CampaignReplyMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__campaign_reply_message
     *
     * @mbg.generated Thu May 10 08:22:09 EDT 2018
     */
    int updateByPrimaryKey(CampaignReplyMessage record);
}