package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.EmailGroup;
import com.bryllyant.kona.app.entity.EmailGroupExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmailGroupMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    long countByExample(EmailGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int deleteByExample(EmailGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int insert(EmailGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int insertSelective(EmailGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    List<EmailGroup> selectByExample(EmailGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    EmailGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByExampleSelective(@Param("record") EmailGroup record, @Param("example") EmailGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByExample(@Param("record") EmailGroup record, @Param("example") EmailGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByPrimaryKeySelective(EmailGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_group
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByPrimaryKey(EmailGroup record);
}