package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.EmailTemplate;
import com.bryllyant.kona.app.entity.EmailTemplateExample;
import com.bryllyant.kona.data.dao.KMyBatisMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailTemplateMapper extends com.bryllyant.kona.data.dao.KMyBatisMapper<EmailTemplate, EmailTemplateExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    long countByExample(EmailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    int deleteByExample(EmailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    int insert(EmailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    int insertSelective(EmailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    List<EmailTemplate> selectByExampleWithBLOBs(EmailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    List<EmailTemplate> selectByExample(EmailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    EmailTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    int updateByExampleSelective(@Param("record") EmailTemplate record, @Param("example") EmailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    int updateByExampleWithBLOBs(@Param("record") EmailTemplate record, @Param("example") EmailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    int updateByExample(@Param("record") EmailTemplate record, @Param("example") EmailTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    int updateByPrimaryKeySelective(EmailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    int updateByPrimaryKeyWithBLOBs(EmailTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__email_template
     *
     * @mbg.generated Sat May 26 14:51:47 EDT 2018
     */
    int updateByPrimaryKey(EmailTemplate record);
}