package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.EntityNameRule;
import com.bryllyant.kona.app.entity.EntityNameRuleExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EntityNameRuleMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    long countByExample(EntityNameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int deleteByExample(EntityNameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int insert(EntityNameRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int insertSelective(EntityNameRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    List<EntityNameRule> selectByExample(EntityNameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    EntityNameRule selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByExampleSelective(@Param("record") EntityNameRule record, @Param("example") EntityNameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByExample(@Param("record") EntityNameRule record, @Param("example") EntityNameRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByPrimaryKeySelective(EntityNameRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__entity_name_rule
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByPrimaryKey(EntityNameRule record);
}