package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.Invoice;
import com.bryllyant.kona.app.entity.InvoiceExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InvoiceMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    long countByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int deleteByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int insert(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int insertSelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    List<Invoice> selectByExample(InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    Invoice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByExampleSelective(@Param("record") Invoice record, @Param("example") InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByExample(@Param("record") Invoice record, @Param("example") InvoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByPrimaryKeySelective(Invoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__invoice
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByPrimaryKey(Invoice record);
}