package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.NotificationDelivery;
import com.bryllyant.kona.app.entity.NotificationDeliveryExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NotificationDeliveryMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    long countByExample(NotificationDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int deleteByExample(NotificationDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int insert(NotificationDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int insertSelective(NotificationDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    List<NotificationDelivery> selectByExample(NotificationDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    NotificationDelivery selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByExampleSelective(@Param("record") NotificationDelivery record, @Param("example") NotificationDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByExample(@Param("record") NotificationDelivery record, @Param("example") NotificationDeliveryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByPrimaryKeySelective(NotificationDelivery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__notification_delivery
     *
     * @mbg.generated Sun Nov 19 04:45:21 EST 2017
     */
    int updateByPrimaryKey(NotificationDelivery record);
}