package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.Promo;
import com.bryllyant.kona.app.entity.PromoExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromoMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    long countByExample(PromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int deleteByExample(PromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int insert(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int insertSelective(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    List<Promo> selectByExample(PromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    Promo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByExampleSelective(@Param("record") Promo record, @Param("example") PromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByExample(@Param("record") Promo record, @Param("example") PromoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByPrimaryKeySelective(Promo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__promo
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByPrimaryKey(Promo record);
}