package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.PushNotificationMessage;
import com.bryllyant.kona.app.entity.PushNotificationMessageExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PushNotificationMessageMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    long countByExample(PushNotificationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    int deleteByExample(PushNotificationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    int insert(PushNotificationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    int insertSelective(PushNotificationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    List<PushNotificationMessage> selectByExampleWithBLOBs(PushNotificationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    List<PushNotificationMessage> selectByExample(PushNotificationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    PushNotificationMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    int updateByExampleSelective(@Param("record") PushNotificationMessage record, @Param("example") PushNotificationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") PushNotificationMessage record, @Param("example") PushNotificationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    int updateByExample(@Param("record") PushNotificationMessage record, @Param("example") PushNotificationMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    int updateByPrimaryKeySelective(PushNotificationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PushNotificationMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_message
     *
     * @mbg.generated Sun Feb 04 14:51:05 EST 2018
     */
    int updateByPrimaryKey(PushNotificationMessage record);
}