package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.PushNotificationDevice;
import com.bryllyant.kona.app.entity.PushNotificationDeviceExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PushNotificationDeviceMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    long countByExample(PushNotificationDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int deleteByExample(PushNotificationDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int insert(PushNotificationDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int insertSelective(PushNotificationDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    List<PushNotificationDevice> selectByExample(PushNotificationDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    PushNotificationDevice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByExampleSelective(@Param("record") PushNotificationDevice record, @Param("example") PushNotificationDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByExample(@Param("record") PushNotificationDevice record, @Param("example") PushNotificationDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByPrimaryKeySelective(PushNotificationDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__push_notification_device
     *
     * @mbg.generated Fri Nov 24 12:43:45 EST 2017
     */
    int updateByPrimaryKey(PushNotificationDevice record);

    List<PushNotificationDevice> fetchByUserIds(
            @Param("userIds") List<Long> userIdList,
            @Param("sandbox") boolean sandbox
    );
}           
