package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.Redirect;
import com.bryllyant.kona.app.entity.RedirectExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RedirectMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    long countByExample(RedirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    int deleteByExample(RedirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    int insert(Redirect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    int insertSelective(Redirect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    List<Redirect> selectByExample(RedirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    Redirect selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    int updateByExampleSelective(@Param("record") Redirect record, @Param("example") RedirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    int updateByExample(@Param("record") Redirect record, @Param("example") RedirectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    int updateByPrimaryKeySelective(Redirect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__redirect
     *
     * @mbg.generated Mon Mar 05 14:06:42 EST 2018
     */
    int updateByPrimaryKey(Redirect record);
}