package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.ShortUrl;
import com.bryllyant.kona.app.entity.ShortUrlExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ShortUrlMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    long countByExample(ShortUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int deleteByExample(ShortUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int insert(ShortUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int insertSelective(ShortUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    List<ShortUrl> selectByExample(ShortUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    ShortUrl selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByExampleSelective(@Param("record") ShortUrl record, @Param("example") ShortUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByExample(@Param("record") ShortUrl record, @Param("example") ShortUrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByPrimaryKeySelective(ShortUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__short_url
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByPrimaryKey(ShortUrl record);
}