package com.bryllyant.kona.app.dao;

import com.bryllyant.kona.app.entity.SupportMessage;
import com.bryllyant.kona.app.entity.SupportMessageExample;
import com.bryllyant.kona.data.dao.KMyBatisDao;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SupportMessageMapper extends KMyBatisDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    long countByExample(SupportMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int deleteByExample(SupportMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int insert(SupportMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int insertSelective(SupportMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    List<SupportMessage> selectByExample(SupportMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    SupportMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByExampleSelective(@Param("record") SupportMessage record, @Param("example") SupportMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByExample(@Param("record") SupportMessage record, @Param("example") SupportMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByPrimaryKeySelective(SupportMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kona__support_message
     *
     * @mbg.generated Tue Oct 17 16:06:32 EDT 2017
     */
    int updateByPrimaryKey(SupportMessage record);
}