-- // seed auth tables
-- Migration SQL that makes the change goes here.

INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'anal',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'anus',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'arse',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'ass',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'ballsack',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'balls',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'bastard',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'bitch',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'biatch',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'bloody',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'blowjob',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'blow job',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'bollock',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'bollok',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'boner',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'boob',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'bugger',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'bum',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'butt',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'buttplug',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'clitoris',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'cock',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'coon',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'crap',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'cunt',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'damn',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'dick',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'dildo',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'dyke',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'fag',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'feck',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'fellate',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'fellatio',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'felching',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'fuck',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'f u c k',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'fudgepacker',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'fudge packer',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'flange',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'Goddamn',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'God damn',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'hell',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'homo',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'jerk',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'jizz',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'knobend',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'knob end',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'labia',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'lmao',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'lmfao',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'muff',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'nigger',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'nigga',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'omg',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'penis',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'piss',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'poop',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'prick',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'pube',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'pussy',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'queer',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'scrotum',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'sex',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'shit',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'s hit',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'sh1t',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'slut',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'smegma',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'spunk',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'tit',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'tosser',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'turd',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'twat',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'vagina',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'wank',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'whore',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'wtf',1,0,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'start',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'stop',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'begin',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'end',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'snapchat',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'instagram',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'linkedin',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'twitter',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'facebook',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'google',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'google+',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'email',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'sms',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'text',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'www',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'web',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'system',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'rpc',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'login',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'logout',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'app',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'apps',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'route',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'routes',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'admin',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'qa',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'setting',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'settings',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'docs',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'api',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'file',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'files',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'download',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'downloads',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'about',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'legal',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'terms',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'privacy',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'confirm',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'alert',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'alerts',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'threat',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'threats',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'asset',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'assets',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'promo',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'promos',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'partner',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'partners',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'account',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'user',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'jdoe',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'johndoe',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'janedoe',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'john.doe',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'jane.doe',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'service',0,1,now(),now());
INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'services',0,1,now(),now());
-- INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'sharif',0,1,now(),now());
-- INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'violet',0,1,now(),now());
-- INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'chris',0,1,now(),now());
-- INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'christopher',0,1,now(),now());
-- INSERT INTO `kona__entity_name_rule` VALUES (NULL,replace(uuid(),'-',''),'aiden',0,1,now(),now());


-- //@UNDO
-- SQL to undo the change goes here.
delete from kona__entity_name_rule;
